<?php

	//Loglevels
	define('LOG_NO',5);
	define('LOG_FATAL',4);
	define('LOG_ERROR',3);
	define('LOG_WARNING',2);
	define('LOG_MESSAGE',1);
	define('LOG_INFO',0);

	//Logtargets
	define('LOG_HTML',1);
	define('LOG_COUT',2);
	define('LOG_STRING',4);

	//Skinningtypes
	define('SKIN_SOFTWARE',2);
	define('SKIN_HARDWARE',1);

	//Lightsourcestypes
	define('LIGHT_DIRECTIONAL',1);
	define('LIGHT_POINT',2);
	define('LIGHT_SPOT',3);

	//Texturefiltering
	define('TF_NONE',0);
	define('TF_POINT',1);
	define('TF_LINEAR',2);
	define('TF_ANISOTROPIC',3);
	define('TF_ANISOTROPICX4',4);
	define('TF_ANISOTROPICX8',5);
	define('TF_ANISOTROPICX16',6);

	//PixelShaderversions
	define('PS_1_1',0);
	define('PS_1_2',1);
	define('PS_1_3',2);
	define('PS_1_4',3);
	define('PS_2_0',4);
	define('PS_3_0',5);

	//VertexShaderversions
	define('VS_1_1',0);
	define('VS_2_0',1);
	define('VS_3_0',2);

	//Matrixsemantics
	define('WORLD',0);
	define('WORLDVIEWPROJ',1);
	define('VIEWPROJ',2);
	define('VIEW',3);
	define('PROJ',4);
	define('WORLDVIEW',5);
	define('VIEWINVERSE',6);
	define('WORLDINVERSETRANSPOSE',15);
	define('WORLDINVERSE',16);
	define('WORLDTRANSPOSE',17);
	define('VIEWPROJINVERSE',18);
	define('VIEWPROJINVERSETRANSPOSE',19);
	define('VIEWTRANSPOSE',20);
	define('VIEWINVRSETRANSPOSE',21);
	define('PROJINVERSE',22);
	define('PROJTRANSPOSE',23);
	define('PROJINVRSETRANSPOSE',24);
	define('WORLDVIEWPROJTRANSPOSE',25);
	define('WORLDVIEWPROJINVERSE',26);
	define('WORLDVIEWPROJINVERSETRANSPOSE',27);
	define('WORLDVIEWTRANSPOSE',28);
	define('WORLDVIEWINVERSE',29);
	define('WORLDVIEWINVERSETRANSPOSE',30);

	//Antialiasingtypes
	define('AANONE',0);
	define('AA2SAMPLES',1);
	define('AA3SAMPLES',2);
	define('AA4SAMPLES',3);
	define('AA5SAMPLES',4);
	define('AA6SAMPLES',5);
	define('AA7SAMPLES',6);
	define('AA8SAMPLES',7);
	define('AA9SAMPLES',8);
	define('AA10SAMPLES',9);
	define('AA11SAMPLES',10);
	define('AA12SAMPLES',11);
	define('AA13SAMPLES',12);
	define('AA14SAMPLES',13);
	define('AA15SAMPLES',14);
	define('AA16SAMPLES',15);

	//Camerafogmode
	define('FOG_NONE',0);
	define('FOG_LINEAR',1);

	//Cameraprojectionmode
	define('PROJ_DISABLE',0);
	define('PROJ_PERSPECTIVE	',1);
	define('PROJ_ORTHOGRAPHIC',2);

	//EntityFXflags
	define('FX_NOTHING',0);
	define('FX_FULLBRIGHT',1);
	define('FX_VERTEXCOLOR',2);
	define('FX_FLATSHADED',4);
	define('FX_DISABLEFOG',8);
	define('FX_DISABLECULLING',16);

	//Entityblendingmodes
	define('BLEND_ALPHA',1);
	define('BLEND_MULTIPLY',2);
	define('BLEND_ADD',3);
	define('BLEND_PUREADD',4);

	//Comparefunctions
	define('CMP_NEVER',1);
	define('CMP_LESS',2);
	define('CMP_EQUAL',3);
	define('CMP_LESSEQUAL',4);
	define('CMP_GREATER',5);
	define('CMP_NOTEQUAL',6);
	define('CMP_GREATEREQUAL',7);
	define('CMP_ALWAYS',8);

	//Axis
	define('AXIS_X',1);
	define('AXIS_Y',2);
	define('AXIS_Z',3);

	//Textureloadingflags
	define('FLAGS_COLOR',1);
	define('FLAGS_ALPHA',2);
	define('FLAGS_MASKED',4);
	define('FLAGS_MIPMAPPED',8);
	define('FLAGS_CLAMPU',16);
	define('FLAGS_CLAMPV',32);
	define('FLAGS_SPHERICALENVMAP',64);
	define('FLAGS_CUBICENVMAP',128);
	define('FLAGS_R32F',256);
	define('FLAGS_SKIPCACHE',512);
	define('FLAGS_VOLUMETEXTURE',1024);
	define('FLAGS_ARBG16F',2048);
	define('FLAGS_ARBG32F',4096);

	//Textureblendingmodes
	define('TEXBLEND_NONE',0);
	define('TEXBLEND_ALPHA',1);
	define('TEXBLEND_MULTIPLY',2);
	define('TEXBLEND_ADD',3);
	define('TEXBLEND_DOT3',4);
	define('TEXBLEND_LIGHTMAP',5);
	define('TEXBLEND_SEPARATEALPHA',6);

	//Cubemapfaces
	define('FACE_LEFT',0);
	define('FACE_FORWARD',1);
	define('FACE_RIGHT',2);
	define('FACE_BACKWARD',3);
	define('FACE_UP',4);
	define('FACE_DOWN',5);

	//Entityanimationtypes
	define('ANIMATION_STOP',0);
	define('ANIMATION_LOOP',1);
	define('ANIMATION_PINGPONG',2);
	define('ANIMATION_ONE',3);

	//Collisiontypes
	define('SPHERETOSHPHERE',1);
	define('SPHERETOBOX',3);
	define('SPHERETOTRIMESH',2);

	//Collisionresponestypes
	define('RESPONSE_STOP',1);
	define('RESPONSE_SLIDING',2);
	define('RESPONSE_SLIDING_DOWNLOCK',3);

	//Entitypickingmodes
	define('PICK_NONE',0);
	define('PICK_SPHERE',1);
	define('PICK_TRIMESH',2);
	define('PICK_BOX',3);

	//Spriteviewmodes
	define('SPRITE_FIXED',1);
	define('SPRITE_FREE',2);
	define('SPRITE_FREEROLL',3);
	define('SPRITE_FIXEDYAW',4);

	//Joysticktypes
	define('JOY_NONE',0);
	define('JOY_DIGITAL',1);
	define('JOY_ANALOG',2);

	//Cubemaprenderingmodes
	define('CUBEMAP_SPECULAR',1);
	define('CUBEMAP_DIFFUSE',2);
	define('CUBEMAP_REFRACTION',3);

	//Shadow'sblurlevels
	define('SHADOWS_BLUR_NONE',0);
	define('SHADOWS_BLUR_3',1);
	define('SHADOWS_BLUR_5',2);
	define('SHADOWS_BLUR_7',3);
	define('SHADOWS_BLUR_11',4);
	define('SHADOWS_BLUR_13',5);


	//primitivestypes
	define('PRIMITIVE_POINTLIST',1);
	define('PRIMITIVE_LINELIST',2);
	define('PRIMITIVE_LINESTRIP',3);
	define('PRIMITIVE_TRIANGLELIST',4);
	define('PRIMITIVE_TRIANGLESTRIP',5);
	define('PRIMITIVE_TRIANGLEFAN',6);
	
	//lineseparatortypes
	define('LS_NUL		',0);
	define('LS_CR		',1);
	define('LS_LF		',2);
	define('LS_CRLF	',3);

	//Scancodesforkeyboardandmouse
	define('MOUSE_LEFT',1);
	define('MOUSE_RIGHT',2);
	define('MOUSE_MIDDLE',3);
	define('MOUSE4',4);
	define('MOUSE5',5);
	define('MOUSE6',6);
	define('MOUSE7',7);
	define('MOUSE8',8);
	define('KEY_ESCAPE',1);
	define('KEY_1',2);
	define('KEY_2',3);
	define('KEY_3',4);
	define('KEY_4',5);
	define('KEY_5',6);
	define('KEY_6',7);
	define('KEY_7',8);
	define('KEY_8',9);
	define('KEY_9',10);
	define('KEY_0',11);
	define('KEY_MINUS',12);
	define('KEY_EQUALS',13);
	define('KEY_BACK',14);
	define('KEY_TAB',15);
	define('KEY_Q',16);
	define('KEY_W',17);
	define('KEY_E',18);
	define('KEY_R',19);
	define('KEY_T',20);
	define('KEY_Y',21);
	define('KEY_U',22);
	define('KEY_I',23);
	define('KEY_O',24);
	define('KEY_P',25);
	define('KEY_LBRACKET',26);
	define('KEY_RBRACKET',27);
	define('KEY_RETURN',28);
	define('KEY_LCONTROL',29);
	define('KEY_RCONTROL',157);
	define('KEY_A',30);
	define('KEY_S',31);
	define('KEY_D',32);
	define('KEY_F',33);
	define('KEY_G',34);
	define('KEY_H',35);
	define('KEY_J',36);
	define('KEY_K',37);
	define('KEY_L',38);
	define('KEY_SEMICOLON',39);
	define('KEY_APOSTROPHE',40);
	define('KEY_GRAVE',41);
	define('KEY_LSHIFT',42);
	define('KEY_BACKSLASH',43);
	define('KEY_Z',44);
	define('KEY_X',45);
	define('KEY_C',46);
	define('KEY_V',47);
	define('KEY_B',48);
	define('KEY_N',49);
	define('KEY_M',50);
	define('KEY_COMMA',51);
	define('KEY_PERIOD',52);
	define('KEY_SLASH',53);
	define('KEY_RSHIFT',54);
	define('KEY_MULTIPLY',55);
	define('KEY_MENU',56);
	define('KEY_SPACE',57);
	define('KEY_F1',59);
	define('KEY_F2',60);
	define('KEY_F3',61);
	define('KEY_F4',62);
	define('KEY_F5',63);
	define('KEY_F6',64);
	define('KEY_F7',65);
	define('KEY_F8',66);
	define('KEY_F9',67);
	define('KEY_F10',68);
	define('KEY_NUMLOCK',69);
	define('KEY_SCROLL',70);
	define('KEY_NUMPAD7',71);
	define('KEY_NUMPAD8',72);
	define('KEY_NUMPAD9',73);
	define('KEY_SUBTRACT',74);
	define('KEY_NUMPAD4',75);
	define('KEY_NUMPAD5',76);
	define('KEY_NUMPAD6',77);
	define('KEY_ADD',78);
	define('KEY_NUMPAD1',79);
	define('KEY_NUMPAD2',80);
	define('KEY_NUMPAD3',81);
	define('KEY_NUMPAD0',82);
	define('KEY_DECIMAL',83);
	define('KEY_TILD',86);
	define('KEY_F11',87);
	define('KEY_F12',88);
	define('KEY_NUMPADENTER',156);
	define('KEY_RMENU',221);
	define('KEY_PAUSE',197);
	define('KEY_HOME',199);
	define('KEY_UP',200);
	define('KEY_PRIOR',201);
	define('KEY_LEFT',203);
	define('KEY_RIGHT',205);
	define('KEY_END',207);
	define('KEY_DOWN',208);
	define('KEY_NEXT',209);
	define('KEY_INSERT',210);
	define('KEY_DELETE',211);
	define('KEY_LWIN',219);
	define('KEY_RWIN',220);
	define('KEY_BACKSPACE',KEY_BACK);
	define('KEY_NUMPADSTAR',KEY_MULTIPLY);
	define('KEY_LALT',184);
	define('KEY_CAPSLOCK',58);
	define('KEY_NUMPADMINUS',KEY_SUBTRACT);
	define('KEY_NUMPADPLUS',KEY_ADD);
	define('KEY_NUMPADPERIOD',KEY_DECIMAL);
	define('KEY_DIVIDE',181);
	define('KEY_NUMPADSLASH',KEY_DIVIDE);
	define('KEY_RALT',56);
	define('KEY_UPARROW',KEY_UP);
	define('KEY_PGUP',KEY_PRIOR);
	define('KEY_LEFTARROW',KEY_LEFT);
	define('KEY_RIGHTARROW',KEY_RIGHT);
	define('KEY_DOWNARROW',KEY_DOWN);
	define('KEY_PGDN',KEY_NEXT);
	
	

	xRegisterFunction("int xCreate3DLine(float, float, float, float, float, float, int, int, int, int, int)", xGetFunctionAddress("xCreate3DLine"));
	xRegisterFunction("void x3DLineOrigin(int, float, float, float, int)", xGetFunctionAddress("x3DLineOrigin"));
	xRegisterFunction("void x3DLineAddNode(int, float, float, float, int)", xGetFunctionAddress("x3DLineAddNode"));
	xRegisterFunction("void x3DLineColor(int, int, int, int, int)", xGetFunctionAddress("x3DLineColor"));
	xRegisterFunction("void x3DLineUseZBuffer(int, int)", xGetFunctionAddress("x3DLineUseZBuffer"));
	xRegisterFunction("float x3DLineOriginX(int, int)", xGetFunctionAddress("x3DLineOriginX"));
	xRegisterFunction("float x3DLineOriginY(int, int)", xGetFunctionAddress("x3DLineOriginY"));
	xRegisterFunction("float x3DLineOriginZ(int, int)", xGetFunctionAddress("x3DLineOriginZ"));
	xRegisterFunction("int x3DLineNodesCount(int)", xGetFunctionAddress("x3DLineNodesCount"));
	xRegisterFunction("float x3DLineNodeX(int, int, int)", xGetFunctionAddress("x3DLineNodeX"));
	xRegisterFunction("float x3DLineNodeY(int, int, int)", xGetFunctionAddress("x3DLineNodeY"));
	xRegisterFunction("float x3DLineNodeZ(int, int, int)", xGetFunctionAddress("x3DLineNodeZ"));
	xRegisterFunction("int x3DLineRed(int)", xGetFunctionAddress("x3DLineRed"));
	xRegisterFunction("int x3DLineGreen(int)", xGetFunctionAddress("x3DLineGreen"));
	xRegisterFunction("int x3DLineBlue(int)", xGetFunctionAddress("x3DLineBlue"));
	xRegisterFunction("int x3DLineAlpha(int)", xGetFunctionAddress("x3DLineAlpha"));
	xRegisterFunction("int xGet3DLineUseZBuffer(int)", xGetFunctionAddress("xGet3DLineUseZBuffer"));
	xRegisterFunction("void xDelete3DLineNode(int, int)", xGetFunctionAddress("xDelete3DLineNode"));
	xRegisterFunction("void xClear3DLine(int)", xGetFunctionAddress("xClear3DLine"));
	xRegisterFunction("int xLoadBrush(charsArray, int, float, float)", xGetFunctionAddress("xLoadBrush"));
	xRegisterFunction("int xCreateBrush(float, float, float)", xGetFunctionAddress("xCreateBrush"));
	xRegisterFunction("void xFreeBrush(int)", xGetFunctionAddress("xFreeBrush"));
	xRegisterFunction("int xGetBrushTexture(int, int)", xGetFunctionAddress("xGetBrushTexture"));
	xRegisterFunction("void xBrushColor(int, int, int, int)", xGetFunctionAddress("xBrushColor"));
	xRegisterFunction("void xBrushAlpha(int, float)", xGetFunctionAddress("xBrushAlpha"));
	xRegisterFunction("void xBrushShininess(int, float)", xGetFunctionAddress("xBrushShininess"));
	xRegisterFunction("void xBrushBlend(int, int)", xGetFunctionAddress("xBrushBlend"));
	xRegisterFunction("void xBrushFX(int, int)", xGetFunctionAddress("xBrushFX"));
	xRegisterFunction("void xBrushTexture(int, int, int, int)", xGetFunctionAddress("xBrushTexture"));
	xRegisterFunction("charsArray xGetBrushName(int)", xGetFunctionAddress("xGetBrushName"));
	xRegisterFunction("void xBrushName(int, charsArray)", xGetFunctionAddress("xBrushName"));
	xRegisterFunction("float xGetBrushAlpha(int)", xGetFunctionAddress("xGetBrushAlpha"));
	xRegisterFunction("int xGetBrushBlend(int)", xGetFunctionAddress("xGetBrushBlend"));
	xRegisterFunction("int xGetBrushRed(int)", xGetFunctionAddress("xGetBrushRed"));
	xRegisterFunction("int xGetBrushGreen(int)", xGetFunctionAddress("xGetBrushGreen"));
	xRegisterFunction("int xGetBrushBlue(int)", xGetFunctionAddress("xGetBrushBlue"));
	xRegisterFunction("int xGetBrushFX(int)", xGetFunctionAddress("xGetBrushFX"));
	xRegisterFunction("float xGetBrushShininess(int)", xGetFunctionAddress("xGetBrushShininess"));
	xRegisterFunction("void xCameraFogMode(int, int)", xGetFunctionAddress("xCameraFogMode"));
	xRegisterFunction("void xCameraFogColor(int, int, int, int)", xGetFunctionAddress("xCameraFogColor"));
	xRegisterFunction("void xCameraFogRange(int, float, float)", xGetFunctionAddress("xCameraFogRange"));
	xRegisterFunction("void xCameraClsColor(int, int, int, int)", xGetFunctionAddress("xCameraClsColor"));
	xRegisterFunction("void xCameraProjMode(int, int)", xGetFunctionAddress("xCameraProjMode"));
	xRegisterFunction("void xCameraClsMode(int, int, int)", xGetFunctionAddress("xCameraClsMode"));
	xRegisterFunction("int xSphereInFrustum(int, float, float, float, float)", xGetFunctionAddress("xSphereInFrustum"));
	xRegisterFunction("void xCameraClipPlane(int, int, int, float, float, float, float)", xGetFunctionAddress("xCameraClipPlane"));
	xRegisterFunction("void xCameraRange(int, float, float)", xGetFunctionAddress("xCameraRange"));
	xRegisterFunction("void xCameraViewport(int, int, int, int, int)", xGetFunctionAddress("xCameraViewport"));
	xRegisterFunction("void xCameraCropViewport(int, int, int, int, int)", xGetFunctionAddress("xCameraCropViewport"));
	xRegisterFunction("int xCreateCamera(int)", xGetFunctionAddress("xCreateCamera"));
	xRegisterFunction("void xCameraProject(int, float, float, float)", xGetFunctionAddress("xCameraProject"));
	xRegisterFunction("void xCameraProject2D(int, int, int, float)", xGetFunctionAddress("xCameraProject2D"));
	xRegisterFunction("float xProjectedX()", xGetFunctionAddress("xProjectedX"));
	xRegisterFunction("float xProjectedY()", xGetFunctionAddress("xProjectedY"));
	xRegisterFunction("float xProjectedZ()", xGetFunctionAddress("xProjectedZ"));
	xRegisterFunction("int xGetViewMatrix(int)", xGetFunctionAddress("xGetViewMatrix"));
	xRegisterFunction("int xGetProjectionMatrix(int)", xGetFunctionAddress("xGetProjectionMatrix"));
	xRegisterFunction("void xCameraZoom(int, float)", xGetFunctionAddress("xCameraZoom"));
	xRegisterFunction("int xGetViewProjMatrix(int)", xGetFunctionAddress("xGetViewProjMatrix"));
	xRegisterFunction("void xCollisions(int, int, int, int)", xGetFunctionAddress("xCollisions"));
	xRegisterFunction("void xClearCollisions()", xGetFunctionAddress("xClearCollisions"));
	xRegisterFunction("void xResetEntity(int)", xGetFunctionAddress("xResetEntity"));
	xRegisterFunction("void xEntityRadius(int, float, float)", xGetFunctionAddress("xEntityRadius"));
	xRegisterFunction("void xEntityBox(int, float, float, float, float, float, float)", xGetFunctionAddress("xEntityBox"));
	xRegisterFunction("void xEntityType(int, int, int)", xGetFunctionAddress("xEntityType"));
	xRegisterFunction("int xEntityCollided(int, int)", xGetFunctionAddress("xEntityCollided"));
	xRegisterFunction("int xCountCollisions(int)", xGetFunctionAddress("xCountCollisions"));
	xRegisterFunction("float xCollisionX(int, int)", xGetFunctionAddress("xCollisionX"));
	xRegisterFunction("float xCollisionY(int, int)", xGetFunctionAddress("xCollisionY"));
	xRegisterFunction("float xCollisionZ(int, int)", xGetFunctionAddress("xCollisionZ"));
	xRegisterFunction("float xCollisionNX(int, int)", xGetFunctionAddress("xCollisionNX"));
	xRegisterFunction("float xCollisionNY(int, int)", xGetFunctionAddress("xCollisionNY"));
	xRegisterFunction("float xCollisionNZ(int, int)", xGetFunctionAddress("xCollisionNZ"));
	xRegisterFunction("float xCollisionTime(int, int)", xGetFunctionAddress("xCollisionTime"));
	xRegisterFunction("int xCollisionEntity(int, int)", xGetFunctionAddress("xCollisionEntity"));
	xRegisterFunction("int xCollisionSurface(int, int)", xGetFunctionAddress("xCollisionSurface"));
	xRegisterFunction("int xCollisionTriangle(int, int)", xGetFunctionAddress("xCollisionTriangle"));
	xRegisterFunction("int xGetEntityType(int)", xGetFunctionAddress("xGetEntityType"));
	xRegisterFunction("void xRenderPostEffect(int)", xGetFunctionAddress("xRenderPostEffect"));
	xRegisterFunction("int xCreatePostEffectPoly(int, int)", xGetFunctionAddress("xCreatePostEffectPoly"));
	xRegisterFunction("int xGetFunctionAddress(charsArray)", xGetFunctionAddress("xGetFunctionAddress"));
	xRegisterFunction("int xLoadFXFile(charsArray)", xGetFunctionAddress("xLoadFXFile"));
	xRegisterFunction("void xFreeEffect(int)", xGetFunctionAddress("xFreeEffect"));
	xRegisterFunction("void xSetEntityEffect(int, int, int)", xGetFunctionAddress("xSetEntityEffect"));
	xRegisterFunction("void xSetSurfaceEffect(int, int, int)", xGetFunctionAddress("xSetSurfaceEffect"));
	xRegisterFunction("void xSetBonesArrayName(int, charsArray, int)", xGetFunctionAddress("xSetBonesArrayName"));
	xRegisterFunction("void xSurfaceBonesArrayName(int, charsArray, int)", xGetFunctionAddress("xSurfaceBonesArrayName"));
	xRegisterFunction("void xSetEffectInt(int, charsArray, int, int)", xGetFunctionAddress("xSetEffectInt"));
	xRegisterFunction("void xSurfaceEffectInt(int, charsArray, int, int)", xGetFunctionAddress("xSurfaceEffectInt"));
	xRegisterFunction("void xSetEffectFloat(int, charsArray, float, int)", xGetFunctionAddress("xSetEffectFloat"));
	xRegisterFunction("void xSurfaceEffectFloat(int, charsArray, float, int)", xGetFunctionAddress("xSurfaceEffectFloat"));
	xRegisterFunction("void xSetEffectBool(int, charsArray, int, int)", xGetFunctionAddress("xSetEffectBool"));
	xRegisterFunction("void xSurfaceEffectBool(int, charsArray, int, int)", xGetFunctionAddress("xSurfaceEffectBool"));
	xRegisterFunction("void xSetEffectVector(int, charsArray, float, float, float, float, int)", xGetFunctionAddress("xSetEffectVector"));
	xRegisterFunction("void xSurfaceEffectVector(int, charsArray, float, float, float, float, int)", xGetFunctionAddress("xSurfaceEffectVector"));
	xRegisterFunction("void xSetEffectVectorArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSetEffectVectorArray"));
	xRegisterFunction("void xSurfaceEffectVectorArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSurfaceEffectVectorArray"));
	xRegisterFunction("void xSurfaceEffectMatrixArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSurfaceEffectMatrixArray"));
	xRegisterFunction("void xSurfaceEffectFloatArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSurfaceEffectFloatArray"));
	xRegisterFunction("void xSurfaceEffectIntArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSurfaceEffectIntArray"));
	xRegisterFunction("void xSetEffectMatrixArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSetEffectMatrixArray"));
	xRegisterFunction("void xSetEffectFloatArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSetEffectFloatArray"));
	xRegisterFunction("void xSetEffectIntArray(int, charsArray, int, int, int)", xGetFunctionAddress("xSetEffectIntArray"));
	xRegisterFunction("int xCreateBufferVectors(int)", xGetFunctionAddress("xCreateBufferVectors"));
	xRegisterFunction("void xBufferVectorsSetElement(int, int, float, float, float, float)", xGetFunctionAddress("xBufferVectorsSetElement"));
	xRegisterFunction("int xCreateBufferMatrix(int)", xGetFunctionAddress("xCreateBufferMatrix"));
	xRegisterFunction("void xBufferMatrixSetElement(int, int, int)", xGetFunctionAddress("xBufferMatrixSetElement"));
	xRegisterFunction("int xBufferMatrixGetElement(int, int)", xGetFunctionAddress("xBufferMatrixGetElement"));
	xRegisterFunction("int xCreateBufferFloats(int)", xGetFunctionAddress("xCreateBufferFloats"));
	xRegisterFunction("void xBufferFloatsSetElement(int, int, float)", xGetFunctionAddress("xBufferFloatsSetElement"));
	xRegisterFunction("float xBufferFloatsGetElement(int, int)", xGetFunctionAddress("xBufferFloatsGetElement"));
	xRegisterFunction("void xBufferDelete(int)", xGetFunctionAddress("xBufferDelete"));
	xRegisterFunction("void xSetEffectMatrixWithElements(int, charsArray, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, int)", xGetFunctionAddress("xSetEffectMatrixWithElements"));
	xRegisterFunction("void xSetEffectMatrix(int, charsArray, int, int)", xGetFunctionAddress("xSetEffectMatrix"));
	xRegisterFunction("void xSurfaceEffectMatrix(int, charsArray, int, int)", xGetFunctionAddress("xSurfaceEffectMatrix"));
	xRegisterFunction("void xSurfaceEffectMatrixWithElements(int, charsArray, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, int)", xGetFunctionAddress("xSurfaceEffectMatrixWithElements"));
	xRegisterFunction("void xSetEffectEntityTexture(int, charsArray, int, int)", xGetFunctionAddress("xSetEffectEntityTexture"));
	xRegisterFunction("void xSetEffectTexture(int, charsArray, int, int, int)", xGetFunctionAddress("xSetEffectTexture"));
	xRegisterFunction("void xSurfaceEffectTexture(int, charsArray, int, int, int)", xGetFunctionAddress("xSurfaceEffectTexture"));
	xRegisterFunction("void xSurfaceEffectMatrixSemantic(int, charsArray, int, int)", xGetFunctionAddress("xSurfaceEffectMatrixSemantic"));
	xRegisterFunction("void xSetEffectMatrixSemantic(int, charsArray, int, int)", xGetFunctionAddress("xSetEffectMatrixSemantic"));
	xRegisterFunction("void xDeleteSurfaceConstant(int, charsArray, int)", xGetFunctionAddress("xDeleteSurfaceConstant"));
	xRegisterFunction("void xDeleteEffectConstant(int, charsArray, int)", xGetFunctionAddress("xDeleteEffectConstant"));
	xRegisterFunction("void xClearSurfaceConstants(int, int)", xGetFunctionAddress("xClearSurfaceConstants"));
	xRegisterFunction("void xClearEffectConstants(int, int)", xGetFunctionAddress("xClearEffectConstants"));
	xRegisterFunction("void xSetEffectTechnique(int, charsArray, int)", xGetFunctionAddress("xSetEffectTechnique"));
	xRegisterFunction("void xSurfaceTechnique(int, charsArray, int)", xGetFunctionAddress("xSurfaceTechnique"));
	xRegisterFunction("int xValidateEffectTechnique(int, charsArray)", xGetFunctionAddress("xValidateEffectTechnique"));
	xRegisterFunction("void xSetEntityShaderLayer(int, int)", xGetFunctionAddress("xSetEntityShaderLayer"));
	xRegisterFunction("int xGetEntityShaderLayer(int)", xGetFunctionAddress("xGetEntityShaderLayer"));
	xRegisterFunction("void xSetSurfaceShaderLayer(int, int)", xGetFunctionAddress("xSetSurfaceShaderLayer"));
	xRegisterFunction("int xGetSurfaceShaderLayer(int)", xGetFunctionAddress("xGetSurfaceShaderLayer"));
	xRegisterFunction("void xSetFXInt(int, charsArray, int)", xGetFunctionAddress("xSetFXInt"));
	xRegisterFunction("void xSetFXFloat(int, charsArray, float)", xGetFunctionAddress("xSetFXFloat"));
	xRegisterFunction("void xSetFXBool(int, charsArray, int)", xGetFunctionAddress("xSetFXBool"));
	xRegisterFunction("void xSetFXVector(int, charsArray, float, float, float, float)", xGetFunctionAddress("xSetFXVector"));
	xRegisterFunction("void xSetFXVectorArray(int, charsArray, int, int)", xGetFunctionAddress("xSetFXVectorArray"));
	xRegisterFunction("void xSetFXMatrixArray(int, charsArray, int, int)", xGetFunctionAddress("xSetFXMatrixArray"));
	xRegisterFunction("void xSetFXFloatArray(int, charsArray, int, int)", xGetFunctionAddress("xSetFXFloatArray"));
	xRegisterFunction("void xSetFXIntArray(int, charsArray, int, int)", xGetFunctionAddress("xSetFXIntArray"));
	xRegisterFunction("void xSetFXEntityMatrix(int, charsArray, int)", xGetFunctionAddress("xSetFXEntityMatrix"));
	xRegisterFunction("void xSetFXTexture(int, charsArray, int, int)", xGetFunctionAddress("xSetFXTexture"));
	xRegisterFunction("void xSetFXMatrixSemantic(int, charsArray, int)", xGetFunctionAddress("xSetFXMatrixSemantic"));
	xRegisterFunction("void xDeleteFXConstant(int, charsArray)", xGetFunctionAddress("xDeleteFXConstant"));
	xRegisterFunction("void xClearFXConstants(int)", xGetFunctionAddress("xClearFXConstants"));
	xRegisterFunction("void xSetFXTechnique(int, charsArray)", xGetFunctionAddress("xSetFXTechnique"));
	xRegisterFunction("int xCreateEmitter(int, int)", xGetFunctionAddress("xCreateEmitter"));
	xRegisterFunction("void xEmitterEnable(int, int)", xGetFunctionAddress("xEmitterEnable"));
	xRegisterFunction("int xEmitterEnabled(int)", xGetFunctionAddress("xEmitterEnabled"));
	xRegisterFunction("int xEmitterGetPSystem(int)", xGetFunctionAddress("xEmitterGetPSystem"));
	xRegisterFunction("int xEmitterAddParticle(int)", xGetFunctionAddress("xEmitterAddParticle"));
	xRegisterFunction("void xEmitterFreeParticle(int, int)", xGetFunctionAddress("xEmitterFreeParticle"));
	xRegisterFunction("int xEmitterValidateParticle(int, int)", xGetFunctionAddress("xEmitterValidateParticle"));
	xRegisterFunction("int xEmitterCountParticles(int)", xGetFunctionAddress("xEmitterCountParticles"));
	xRegisterFunction("int xEmitterGetParticle(int, int)", xGetFunctionAddress("xEmitterGetParticle"));
	xRegisterFunction("int xEmitterAlive(int)", xGetFunctionAddress("xEmitterAlive"));
	xRegisterFunction("int xExtractAnimSeq(int, int, int, int)", xGetFunctionAddress("xExtractAnimSeq"));
	xRegisterFunction("int xLoadAnimSeq(int, charsArray)", xGetFunctionAddress("xLoadAnimSeq"));
	xRegisterFunction("void xSetAnimSpeed(int, float, charsArray)", xGetFunctionAddress("xSetAnimSpeed"));
	xRegisterFunction("float xAnimSpeed(int, charsArray)", xGetFunctionAddress("xAnimSpeed"));
	xRegisterFunction("int xAnimating(int, charsArray)", xGetFunctionAddress("xAnimating"));
	xRegisterFunction("float xAnimTime(int, charsArray)", xGetFunctionAddress("xAnimTime"));
	xRegisterFunction("void xAnimate(int, int, float, int, float, charsArray)", xGetFunctionAddress("xAnimate"));
	xRegisterFunction("int xAnimSeq(int, charsArray)", xGetFunctionAddress("xAnimSeq"));
	xRegisterFunction("float xAnimLength(int, charsArray)", xGetFunctionAddress("xAnimLength"));
	xRegisterFunction("void xSetAnimTime(int, float, int, charsArray)", xGetFunctionAddress("xSetAnimTime"));
	xRegisterFunction("void xSetAnimFrame(int, float, int, charsArray)", xGetFunctionAddress("xSetAnimFrame"));
	xRegisterFunction("void xEntityAutoFade(int, float, float)", xGetFunctionAddress("xEntityAutoFade"));
	xRegisterFunction("void xEntityOrder(int, int)", xGetFunctionAddress("xEntityOrder"));
	xRegisterFunction("void xFreeEntity(int)", xGetFunctionAddress("xFreeEntity"));
	xRegisterFunction("int xCopyEntity(int, int, int)", xGetFunctionAddress("xCopyEntity"));
	xRegisterFunction("void xPaintEntity(int, int)", xGetFunctionAddress("xPaintEntity"));
	xRegisterFunction("void xEntityShininess(int, float)", xGetFunctionAddress("xEntityShininess"));
	xRegisterFunction("void xEntityPickMode(int, int, int, int)", xGetFunctionAddress("xEntityPickMode"));
	xRegisterFunction("void xEntityTexture(int, int, int, int)", xGetFunctionAddress("xEntityTexture"));
	xRegisterFunction("void xEntityFX(int, int)", xGetFunctionAddress("xEntityFX"));
	xRegisterFunction("int xGetParent(int)", xGetFunctionAddress("xGetParent"));
	xRegisterFunction("void xSetFrustumSphere(int, float, float, float, float)", xGetFunctionAddress("xSetFrustumSphere"));
	xRegisterFunction("void xCalculateFrustumVolume(int)", xGetFunctionAddress("xCalculateFrustumVolume"));
	xRegisterFunction("void xEntityParent(int, int, int)", xGetFunctionAddress("xEntityParent"));
	xRegisterFunction("void xShowEntity(int)", xGetFunctionAddress("xShowEntity"));
	xRegisterFunction("void xHideEntity(int)", xGetFunctionAddress("xHideEntity"));
	xRegisterFunction("void xNameEntity(int, charsArray)", xGetFunctionAddress("xNameEntity"));
	xRegisterFunction("void xSetEntityQuaternion(int, int)", xGetFunctionAddress("xSetEntityQuaternion"));
	xRegisterFunction("void xSetEntityMatrix(int, int)", xGetFunctionAddress("xSetEntityMatrix"));
	xRegisterFunction("void xEntityAlpha(int, float)", xGetFunctionAddress("xEntityAlpha"));
	xRegisterFunction("void xEntityColor(int, int, int, int)", xGetFunctionAddress("xEntityColor"));
	xRegisterFunction("void xEntitySpecularColor(int, int, int, int)", xGetFunctionAddress("xEntitySpecularColor"));
	xRegisterFunction("void xEntityAmbientColor(int, int, int, int)", xGetFunctionAddress("xEntityAmbientColor"));
	xRegisterFunction("void xEntityEmissiveColor(int, int, int, int)", xGetFunctionAddress("xEntityEmissiveColor"));
	xRegisterFunction("void xEntityBlend(int, int)", xGetFunctionAddress("xEntityBlend"));
	xRegisterFunction("void xSetAlphaRef(int, int)", xGetFunctionAddress("xSetAlphaRef"));
	xRegisterFunction("void xSetAlphaFunc(int, int)", xGetFunctionAddress("xSetAlphaFunc"));
	xRegisterFunction("int xCreateInstance(int, int)", xGetFunctionAddress("xCreateInstance"));
	xRegisterFunction("void xFreezeInstances(int, int)", xGetFunctionAddress("xFreezeInstances"));
	xRegisterFunction("int xInstancingAvaliable()", xGetFunctionAddress("xInstancingAvaliable"));
	xRegisterFunction("void xScaleEntity(int, float, float, float, int)", xGetFunctionAddress("xScaleEntity"));
	xRegisterFunction("void xPositionEntity(int, float, float, float, int)", xGetFunctionAddress("xPositionEntity"));
	xRegisterFunction("void xMoveEntity(int, float, float, float, int)", xGetFunctionAddress("xMoveEntity"));
	xRegisterFunction("void xTranslateEntity(int, float, float, float, int)", xGetFunctionAddress("xTranslateEntity"));
	xRegisterFunction("void xRotateEntity(int, float, float, float, int)", xGetFunctionAddress("xRotateEntity"));
	xRegisterFunction("void xTurnEntity(int, float, float, float, int)", xGetFunctionAddress("xTurnEntity"));
	xRegisterFunction("void xPointEntity(int, int, float)", xGetFunctionAddress("xPointEntity"));
	xRegisterFunction("void xAlignToVector(int, float, float, float, int, float)", xGetFunctionAddress("xAlignToVector"));
	xRegisterFunction("float xEntityDistance(int, int)", xGetFunctionAddress("xEntityDistance"));
	xRegisterFunction("float xGetMatElement(int, int, int)", xGetFunctionAddress("xGetMatElement"));
	xRegisterFunction("charsArray xEntityClass(int)", xGetFunctionAddress("xEntityClass"));
	xRegisterFunction("int xGetEntityBrush(int)", xGetFunctionAddress("xGetEntityBrush"));
	xRegisterFunction("float xEntityX(int, int)", xGetFunctionAddress("xEntityX"));
	xRegisterFunction("float xEntityY(int, int)", xGetFunctionAddress("xEntityY"));
	xRegisterFunction("float xEntityZ(int, int)", xGetFunctionAddress("xEntityZ"));
	xRegisterFunction("int xEntityVisible(int, int)", xGetFunctionAddress("xEntityVisible"));
	xRegisterFunction("float xEntityScaleX(int)", xGetFunctionAddress("xEntityScaleX"));
	xRegisterFunction("float xEntityScaleY(int)", xGetFunctionAddress("xEntityScaleY"));
	xRegisterFunction("float xEntityScaleZ(int)", xGetFunctionAddress("xEntityScaleZ"));
	xRegisterFunction("float xEntityRoll(int, int)", xGetFunctionAddress("xEntityRoll"));
	xRegisterFunction("float xEntityYaw(int, int)", xGetFunctionAddress("xEntityYaw"));
	xRegisterFunction("float xEntityPitch(int, int)", xGetFunctionAddress("xEntityPitch"));
	xRegisterFunction("charsArray xEntityName(int)", xGetFunctionAddress("xEntityName"));
	xRegisterFunction("int xCountChildren(int)", xGetFunctionAddress("xCountChildren"));
	xRegisterFunction("int xGetChild(int, int)", xGetFunctionAddress("xGetChild"));
	xRegisterFunction("int xEntityInView(int, int)", xGetFunctionAddress("xEntityInView"));
	xRegisterFunction("int xFindChild(int, charsArray)", xGetFunctionAddress("xFindChild"));
	xRegisterFunction("int xGetEntityMatrix(int)", xGetFunctionAddress("xGetEntityMatrix"));
	xRegisterFunction("float xGetEntityAlpha(int)", xGetFunctionAddress("xGetEntityAlpha"));
	xRegisterFunction("int xGetAlphaRef(int)", xGetFunctionAddress("xGetAlphaRef"));
	xRegisterFunction("int xGetAlphaFunc(int)", xGetFunctionAddress("xGetAlphaFunc"));
	xRegisterFunction("int xEntityRed(int)", xGetFunctionAddress("xEntityRed"));
	xRegisterFunction("int xEntityGreen(int)", xGetFunctionAddress("xEntityGreen"));
	xRegisterFunction("int xEntityBlue(int)", xGetFunctionAddress("xEntityBlue"));
	xRegisterFunction("float xGetEntityShininess(int)", xGetFunctionAddress("xGetEntityShininess"));
	xRegisterFunction("int xGetEntityBlend(int)", xGetFunctionAddress("xGetEntityBlend"));
	xRegisterFunction("int xGetEntityFX(int)", xGetFunctionAddress("xGetEntityFX"));
	xRegisterFunction("int xEntityHidden(int)", xGetFunctionAddress("xEntityHidden"));
	xRegisterFunction("int xMountPackFile(charsArray, charsArray, charsArray)", xGetFunctionAddress("xMountPackFile"));
	xRegisterFunction("void xUnmountPackFile(int)", xGetFunctionAddress("xUnmountPackFile"));
	xRegisterFunction("int xOpenFile(charsArray)", xGetFunctionAddress("xOpenFile"));
	xRegisterFunction("int xReadFile(charsArray)", xGetFunctionAddress("xReadFile"));
	xRegisterFunction("int xWriteFile(charsArray)", xGetFunctionAddress("xWriteFile"));
	xRegisterFunction("void xCloseFile(int)", xGetFunctionAddress("xCloseFile"));
	xRegisterFunction("int xFilePos(int)", xGetFunctionAddress("xFilePos"));
	xRegisterFunction("void xSeekFile(int, int)", xGetFunctionAddress("xSeekFile"));
	xRegisterFunction("int xFileType(charsArray)", xGetFunctionAddress("xFileType"));
	xRegisterFunction("int xFileSize(charsArray)", xGetFunctionAddress("xFileSize"));
	xRegisterFunction("int xReadDir(charsArray)", xGetFunctionAddress("xReadDir"));
	xRegisterFunction("void xCloseDir(int)", xGetFunctionAddress("xCloseDir"));
	xRegisterFunction("charsArray xNextFile(int)", xGetFunctionAddress("xNextFile"));
	xRegisterFunction("charsArray xCurrentDir()", xGetFunctionAddress("xCurrentDir"));
	xRegisterFunction("void xChangeDir(charsArray)", xGetFunctionAddress("xChangeDir"));
	xRegisterFunction("int xCreateDir(charsArray)", xGetFunctionAddress("xCreateDir"));
	xRegisterFunction("int xDeleteDir(charsArray)", xGetFunctionAddress("xDeleteDir"));
	xRegisterFunction("int xCopyFile(charsArray, charsArray)", xGetFunctionAddress("xCopyFile"));
	xRegisterFunction("int xDeleteFile(charsArray)", xGetFunctionAddress("xDeleteFile"));
	xRegisterFunction("int xEof(int)", xGetFunctionAddress("xEof"));
	xRegisterFunction("int xReadByte(int)", xGetFunctionAddress("xReadByte"));
	xRegisterFunction("int xReadShort(int)", xGetFunctionAddress("xReadShort"));
	xRegisterFunction("int xReadInt(int)", xGetFunctionAddress("xReadInt"));
	xRegisterFunction("float xReadFloat(int)", xGetFunctionAddress("xReadFloat"));
	xRegisterFunction("charsArray xReadString(int)", xGetFunctionAddress("xReadString"));
	xRegisterFunction("charsArray xReadLine(int, int)", xGetFunctionAddress("xReadLine"));
	xRegisterFunction("void xWriteByte(int, int)", xGetFunctionAddress("xWriteByte"));
	xRegisterFunction("void xWriteShort(int, int)", xGetFunctionAddress("xWriteShort"));
	xRegisterFunction("void xWriteInt(int, int)", xGetFunctionAddress("xWriteInt"));
	xRegisterFunction("void xWriteFloat(int, float)", xGetFunctionAddress("xWriteFloat"));
	xRegisterFunction("void xWriteString(int, charsArray)", xGetFunctionAddress("xWriteString"));
	xRegisterFunction("void xWriteLine(int, charsArray, int)", xGetFunctionAddress("xWriteLine"));
	xRegisterFunction("int xLoadFont(charsArray, int, int, int, int)", xGetFunctionAddress("xLoadFont"));
	xRegisterFunction("void xText(int, int, charsArray, int, int)", xGetFunctionAddress("xText"));
	xRegisterFunction("void xSetFont(int)", xGetFunctionAddress("xSetFont"));
	xRegisterFunction("void xFreeFont(int)", xGetFunctionAddress("xFreeFont"));
	xRegisterFunction("int xFontWidth()", xGetFunctionAddress("xFontWidth"));
	xRegisterFunction("int xFontHeight()", xGetFunctionAddress("xFontHeight"));
	xRegisterFunction("int xStringWidth(charsArray)", xGetFunctionAddress("xStringWidth"));
	xRegisterFunction("int xStringHeight(charsArray)", xGetFunctionAddress("xStringHeight"));
	xRegisterFunction("int xWinMessage(charsArray)", xGetFunctionAddress("xWinMessage"));
	xRegisterFunction("int xGetMaxPixelShaderVersion()", xGetFunctionAddress("xGetMaxPixelShaderVersion"));
	xRegisterFunction("void xLine(int, int, int, int)", xGetFunctionAddress("xLine"));
	xRegisterFunction("void xRect(int, int, int, int, int)", xGetFunctionAddress("xRect"));
	xRegisterFunction("int xRectsOverlap(int, int, int, int, int, int, int, int)", xGetFunctionAddress("xRectsOverlap"));
	xRegisterFunction("void xViewport(int, int, int, int)", xGetFunctionAddress("xViewport"));
	xRegisterFunction("void xOval(int, int, int, int, int)", xGetFunctionAddress("xOval"));
	xRegisterFunction("void xOrigin(int, int)", xGetFunctionAddress("xOrigin"));
	xRegisterFunction("int xGetMaxVertexShaderVersion()", xGetFunctionAddress("xGetMaxVertexShaderVersion"));
	xRegisterFunction("int xGetMaxAntiAlias()", xGetFunctionAddress("xGetMaxAntiAlias"));
	xRegisterFunction("int xGetMaxTextureFiltering()", xGetFunctionAddress("xGetMaxTextureFiltering"));
	xRegisterFunction("void xSetAntiAliasType(int)", xGetFunctionAddress("xSetAntiAliasType"));
	xRegisterFunction("void xAppTitle(charsArray)", xGetFunctionAddress("xAppTitle"));
	xRegisterFunction("void xSetWND(int)", xGetFunctionAddress("xSetWND"));
	xRegisterFunction("void xSetRenderWindow(int)", xGetFunctionAddress("xSetRenderWindow"));
	xRegisterFunction("void xDestroyRenderWindow()", xGetFunctionAddress("xDestroyRenderWindow"));
	xRegisterFunction("void xFlip()", xGetFunctionAddress("xFlip"));
	xRegisterFunction("int xBackBuffer()", xGetFunctionAddress("xBackBuffer"));
	xRegisterFunction("void xLockBuffer(int)", xGetFunctionAddress("xLockBuffer"));
	xRegisterFunction("void xUnlockBuffer(int)", xGetFunctionAddress("xUnlockBuffer"));
	xRegisterFunction("void xWritePixelFast(int, int, int, int)", xGetFunctionAddress("xWritePixelFast"));
	xRegisterFunction("int xReadPixelFast(int, int, int)", xGetFunctionAddress("xReadPixelFast"));
	xRegisterFunction("int xGetPixels(int)", xGetFunctionAddress("xGetPixels"));
	xRegisterFunction("void xSaveBuffer(int, charsArray)", xGetFunctionAddress("xSaveBuffer"));
	xRegisterFunction("int xGetCurrentBuffer()", xGetFunctionAddress("xGetCurrentBuffer"));
	xRegisterFunction("int xBufferWidth(int)", xGetFunctionAddress("xBufferWidth"));
	xRegisterFunction("int xBufferHeight(int)", xGetFunctionAddress("xBufferHeight"));
	xRegisterFunction("int xCatchTimestamp()", xGetFunctionAddress("xCatchTimestamp"));
	xRegisterFunction("float xGetElapsedTime(int)", xGetFunctionAddress("xGetElapsedTime"));
	xRegisterFunction("void xSetBuffer(int)", xGetFunctionAddress("xSetBuffer"));
	xRegisterFunction("void xSetMRT(int, int, int)", xGetFunctionAddress("xSetMRT"));
	xRegisterFunction("void xUnSetMRT()", xGetFunctionAddress("xUnSetMRT"));
	xRegisterFunction("int xGetNumberRT()", xGetFunctionAddress("xGetNumberRT"));
	xRegisterFunction("int xTextureBuffer(int, int)", xGetFunctionAddress("xTextureBuffer"));
	xRegisterFunction("void xLoadBuffer(int, charsArray)", xGetFunctionAddress("xLoadBuffer"));
	xRegisterFunction("void xWritePixel(int, int, int, int)", xGetFunctionAddress("xWritePixel"));
	xRegisterFunction("void xCopyPixel(int, int, int, int, int, int)", xGetFunctionAddress("xCopyPixel"));
	xRegisterFunction("void xCopyPixelFast(int, int, int, int, int, int)", xGetFunctionAddress("xCopyPixelFast"));
	xRegisterFunction("void xCopyRect(int, int, int, int, int, int, int, int)", xGetFunctionAddress("xCopyRect"));
	xRegisterFunction("int xGraphicsBuffer()", xGetFunctionAddress("xGraphicsBuffer"));
	xRegisterFunction("int xGetColor(int, int)", xGetFunctionAddress("xGetColor"));
	xRegisterFunction("int xReadPixel(int, int, int)", xGetFunctionAddress("xReadPixel"));
	xRegisterFunction("int xGraphicsWidth(int)", xGetFunctionAddress("xGraphicsWidth"));
	xRegisterFunction("int xGraphicsHeight(int)", xGetFunctionAddress("xGraphicsHeight"));
	xRegisterFunction("int xGraphicsDepth()", xGetFunctionAddress("xGraphicsDepth"));
	xRegisterFunction("int xColorRed()", xGetFunctionAddress("xColorRed"));
	xRegisterFunction("int xColorGreen()", xGetFunctionAddress("xColorGreen"));
	xRegisterFunction("int xColorBlue()", xGetFunctionAddress("xColorBlue"));
	xRegisterFunction("void xClsColor(int, int, int, int)", xGetFunctionAddress("xClsColor"));
	xRegisterFunction("void xClearWorld(int, int, int)", xGetFunctionAddress("xClearWorld"));
	xRegisterFunction("void xColor(int, int, int)", xGetFunctionAddress("xColor"));
	xRegisterFunction("void xCls()", xGetFunctionAddress("xCls"));
	xRegisterFunction("void xUpdateWorld(float)", xGetFunctionAddress("xUpdateWorld"));
	xRegisterFunction("void xRenderEntity(int, int, float)", xGetFunctionAddress("xRenderEntity"));
	xRegisterFunction("void xRenderWorld(float, int)", xGetFunctionAddress("xRenderWorld"));
	xRegisterFunction("void xSetAutoTB(int)", xGetFunctionAddress("xSetAutoTB"));
	xRegisterFunction("int xMaxClipPlanes()", xGetFunctionAddress("xMaxClipPlanes"));
	xRegisterFunction("void xWireframe(int)", xGetFunctionAddress("xWireframe"));
	xRegisterFunction("void xDither(int)", xGetFunctionAddress("xDither"));
	xRegisterFunction("void xSetSkinningMethod(int)", xGetFunctionAddress("xSetSkinningMethod"));
	xRegisterFunction("int xTrisRendered()", xGetFunctionAddress("xTrisRendered"));
	xRegisterFunction("int xDIPCounter()", xGetFunctionAddress("xDIPCounter"));
	xRegisterFunction("int xSurfRendered()", xGetFunctionAddress("xSurfRendered"));
	xRegisterFunction("int xEntityRendered()", xGetFunctionAddress("xEntityRendered"));
	xRegisterFunction("void xAmbientLight(int, int, int)", xGetFunctionAddress("xAmbientLight"));
	xRegisterFunction("int xGetFPS()", xGetFunctionAddress("xGetFPS"));
	xRegisterFunction("void xAntiAlias(int)", xGetFunctionAddress("xAntiAlias"));
	xRegisterFunction("void xSetTextureFiltering(int)", xGetFunctionAddress("xSetTextureFiltering"));
	xRegisterFunction("void xStretchRect(int, int, int, int, int, int, int, int, int, int, int)", xGetFunctionAddress("xStretchRect"));
	xRegisterFunction("void xStretchBackBuffer(int, int, int, int, int, int)", xGetFunctionAddress("xStretchBackBuffer"));
	xRegisterFunction("int xGetDevice()", xGetFunctionAddress("xGetDevice"));
	xRegisterFunction("void xReleaseGraphics()", xGetFunctionAddress("xReleaseGraphics"));
	xRegisterFunction("void xShowPointer()", xGetFunctionAddress("xShowPointer"));
	xRegisterFunction("void xHidePointer()", xGetFunctionAddress("xHidePointer"));
	xRegisterFunction("void xCreateDSS(int, int)", xGetFunctionAddress("xCreateDSS"));
	xRegisterFunction("void xDeleteDSS()", xGetFunctionAddress("xDeleteDSS"));
	xRegisterFunction("void xGridColor(int, int, int, int, int, int)", xGetFunctionAddress("xGridColor"));
	xRegisterFunction("void xDrawGrid(float, float, int, int)", xGetFunctionAddress("xDrawGrid"));
	xRegisterFunction("void xDrawBBox(int, int, int, int, int, int)", xGetFunctionAddress("xDrawBBox"));
	xRegisterFunction("void xGraphics3D(int, int, int, int, int)", xGetFunctionAddress("xGraphics3D"));
	xRegisterFunction("void xGraphicsAspectRatio(float)", xGetFunctionAddress("xGraphicsAspectRatio"));
	xRegisterFunction("void xGraphicsBorderColor(int, int, int)", xGetFunctionAddress("xGraphicsBorderColor"));
	xRegisterFunction("int xGetRenderWindow()", xGetFunctionAddress("xGetRenderWindow"));
	xRegisterFunction("void xKey(charsArray)", xGetFunctionAddress("xKey"));
	xRegisterFunction("void xSetEngineSetting(charsArray, charsArray)", xGetFunctionAddress("xSetEngineSetting"));
	xRegisterFunction("charsArray xGetEngineSetting(charsArray)", xGetFunctionAddress("xGetEngineSetting"));
	xRegisterFunction("int xHWInstancingAvailable()", xGetFunctionAddress("xHWInstancingAvailable"));
	xRegisterFunction("int xShaderInstancingAvailable()", xGetFunctionAddress("xShaderInstancingAvailable"));
	xRegisterFunction("void xSetShaderLayer(int)", xGetFunctionAddress("xSetShaderLayer"));
	xRegisterFunction("int xGetShaderLayer()", xGetFunctionAddress("xGetShaderLayer"));
	xRegisterFunction("void xDrawMovementGizmo(float, float, float, int)", xGetFunctionAddress("xDrawMovementGizmo"));
	xRegisterFunction("void xDrawScaleGizmo(float, float, float, int, float, float, float)", xGetFunctionAddress("xDrawScaleGizmo"));
	xRegisterFunction("void xDrawRotationGizmo(float, float, float, int, float, float, float)", xGetFunctionAddress("xDrawRotationGizmo"));
	xRegisterFunction("int xCheckMovementGizmo(float, float, float, int, int, int)", xGetFunctionAddress("xCheckMovementGizmo"));
	xRegisterFunction("int xCheckScaleGizmo(float, float, float, int, int, int)", xGetFunctionAddress("xCheckScaleGizmo"));
	xRegisterFunction("int xCheckRotationGizmo(float, float, float, int, int, int)", xGetFunctionAddress("xCheckRotationGizmo"));
	xRegisterFunction("void xCaptureWorld()", xGetFunctionAddress("xCaptureWorld"));
	xRegisterFunction("int xCountGfxModes()", xGetFunctionAddress("xCountGfxModes"));
	xRegisterFunction("int xGfxModeWidth(int)", xGetFunctionAddress("xGfxModeWidth"));
	xRegisterFunction("int xGfxModeHeight(int)", xGetFunctionAddress("xGfxModeHeight"));
	xRegisterFunction("int xGfxModeDepth(int)", xGetFunctionAddress("xGfxModeDepth"));
	xRegisterFunction("int xGfxModeExists(int, int, int)", xGetFunctionAddress("xGfxModeExists"));
	xRegisterFunction("void xAppWindowFrame(int)", xGetFunctionAddress("xAppWindowFrame"));
	xRegisterFunction("int xMillisecs()", xGetFunctionAddress("xMillisecs"));
	xRegisterFunction("int xDeltaTime(int)", xGetFunctionAddress("xDeltaTime"));
	xRegisterFunction("float xDeltaValue(float, int)", xGetFunctionAddress("xDeltaValue"));
	xRegisterFunction("void xAddDeviceLostCallback(int)", xGetFunctionAddress("xAddDeviceLostCallback"));
	xRegisterFunction("void xDeleteDeviceLostCallback(int)", xGetFunctionAddress("xDeleteDeviceLostCallback"));
	xRegisterFunction("void xImageColor(int, int, int, int)", xGetFunctionAddress("xImageColor"));
	xRegisterFunction("void xImageAlpha(int, float)", xGetFunctionAddress("xImageAlpha"));
	xRegisterFunction("int xImageBuffer(int, int)", xGetFunctionAddress("xImageBuffer"));
	xRegisterFunction("int xCreateImage(int, int, int)", xGetFunctionAddress("xCreateImage"));
	xRegisterFunction("void xGrabImage(int, int, int, int)", xGetFunctionAddress("xGrabImage"));
	xRegisterFunction("void xFreeImage(int)", xGetFunctionAddress("xFreeImage"));
	xRegisterFunction("int xLoadImage(charsArray)", xGetFunctionAddress("xLoadImage"));
	xRegisterFunction("int xLoadAnimImage(charsArray, int, int, int, int)", xGetFunctionAddress("xLoadAnimImage"));
	xRegisterFunction("void xSaveImage(int, charsArray, int)", xGetFunctionAddress("xSaveImage"));
	xRegisterFunction("void xDrawImage(int, int, int, int)", xGetFunctionAddress("xDrawImage"));
	xRegisterFunction("void xDrawImageRect(int, int, int, int, int, int, int, int)", xGetFunctionAddress("xDrawImageRect"));
	xRegisterFunction("void xScaleImage(int, float, float)", xGetFunctionAddress("xScaleImage"));
	xRegisterFunction("void xResizeImage(int, int, int)", xGetFunctionAddress("xResizeImage"));
	xRegisterFunction("void xRotateImage(int, float)", xGetFunctionAddress("xRotateImage"));
	xRegisterFunction("float xImageAngle(int)", xGetFunctionAddress("xImageAngle"));
	xRegisterFunction("int xImageWidth(int)", xGetFunctionAddress("xImageWidth"));
	xRegisterFunction("int xImageHeight(int)", xGetFunctionAddress("xImageHeight"));
	xRegisterFunction("int xImagesCollide(int, int, int, int, int, int, int, int)", xGetFunctionAddress("xImagesCollide"));
	xRegisterFunction("int xImageRectCollide(int, int, int, int, int, int, int, int)", xGetFunctionAddress("xImageRectCollide"));
	xRegisterFunction("int xImageRectOverlap(int, int, int, int, int, int, int)", xGetFunctionAddress("xImageRectOverlap"));
	xRegisterFunction("int xImageXHandle(int)", xGetFunctionAddress("xImageXHandle"));
	xRegisterFunction("int xImageYHandle(int)", xGetFunctionAddress("xImageYHandle"));
	xRegisterFunction("void xHandleImage(int, int, int)", xGetFunctionAddress("xHandleImage"));
	xRegisterFunction("void xMidHandle(int)", xGetFunctionAddress("xMidHandle"));
	xRegisterFunction("void xAutoMidHandle(int)", xGetFunctionAddress("xAutoMidHandle"));
	xRegisterFunction("void xTileImage(int, int, int, int)", xGetFunctionAddress("xTileImage"));
	xRegisterFunction("int xImagesOverlap(int, int, int, int, int, int)", xGetFunctionAddress("xImagesOverlap"));
	xRegisterFunction("void xMaskImage(int, int, int, int)", xGetFunctionAddress("xMaskImage"));
	xRegisterFunction("int xCopyImage(int)", xGetFunctionAddress("xCopyImage"));
	xRegisterFunction("void xDrawBlock(int, int, int, int)", xGetFunctionAddress("xDrawBlock"));
	xRegisterFunction("void xDrawBlockRect(int, int, int, int, int, int, int, int)", xGetFunctionAddress("xDrawBlockRect"));
	xRegisterFunction("int xImageActualWidth(int)", xGetFunctionAddress("xImageActualWidth"));
	xRegisterFunction("int xImageActualHeight(int)", xGetFunctionAddress("xImageActualHeight"));
	xRegisterFunction("void xFlushKeys()", xGetFunctionAddress("xFlushKeys"));
	xRegisterFunction("void xFlushMouse()", xGetFunctionAddress("xFlushMouse"));
	xRegisterFunction("int xKeyHit(int)", xGetFunctionAddress("xKeyHit"));
	xRegisterFunction("int xKeyUp(int)", xGetFunctionAddress("xKeyUp"));
	xRegisterFunction("void xWaitKey()", xGetFunctionAddress("xWaitKey"));
	xRegisterFunction("int xMouseHit(int)", xGetFunctionAddress("xMouseHit"));
	xRegisterFunction("int xKeyDown(int)", xGetFunctionAddress("xKeyDown"));
	xRegisterFunction("int xGetKey()", xGetFunctionAddress("xGetKey"));
	xRegisterFunction("int xMouseDown(int)", xGetFunctionAddress("xMouseDown"));
	xRegisterFunction("int xMouseUp(int)", xGetFunctionAddress("xMouseUp"));
	xRegisterFunction("int xGetMouse()", xGetFunctionAddress("xGetMouse"));
	xRegisterFunction("int xMouseX()", xGetFunctionAddress("xMouseX"));
	xRegisterFunction("int xMouseY()", xGetFunctionAddress("xMouseY"));
	xRegisterFunction("int xMouseZ()", xGetFunctionAddress("xMouseZ"));
	xRegisterFunction("int xMouseXSpeed()", xGetFunctionAddress("xMouseXSpeed"));
	xRegisterFunction("int xMouseYSpeed()", xGetFunctionAddress("xMouseYSpeed"));
	xRegisterFunction("int xMouseZSpeed()", xGetFunctionAddress("xMouseZSpeed"));
	xRegisterFunction("int xMouseSpeed()", xGetFunctionAddress("xMouseSpeed"));
	xRegisterFunction("void xMoveMouse(int, int)", xGetFunctionAddress("xMoveMouse"));
	xRegisterFunction("int xJoyType(int)", xGetFunctionAddress("xJoyType"));
	xRegisterFunction("int xJoyDown(int, int)", xGetFunctionAddress("xJoyDown"));
	xRegisterFunction("int xJoyHit(int, int)", xGetFunctionAddress("xJoyHit"));
	xRegisterFunction("int xGetJoy(int)", xGetFunctionAddress("xGetJoy"));
	xRegisterFunction("void xFlushJoy()", xGetFunctionAddress("xFlushJoy"));
	xRegisterFunction("int xWaitJoy(int)", xGetFunctionAddress("xWaitJoy"));
	xRegisterFunction("float xJoyX(int)", xGetFunctionAddress("xJoyX"));
	xRegisterFunction("float xJoyY(int)", xGetFunctionAddress("xJoyY"));
	xRegisterFunction("float xJoyZ(int)", xGetFunctionAddress("xJoyZ"));
	xRegisterFunction("float xJoyU(int)", xGetFunctionAddress("xJoyU"));
	xRegisterFunction("float xJoyV(int)", xGetFunctionAddress("xJoyV"));
	xRegisterFunction("float xJoyPitch(int)", xGetFunctionAddress("xJoyPitch"));
	xRegisterFunction("float xJoyYaw(int)", xGetFunctionAddress("xJoyYaw"));
	xRegisterFunction("float xJoyRoll(int)", xGetFunctionAddress("xJoyRoll"));
	xRegisterFunction("float xJoyHat(int)", xGetFunctionAddress("xJoyHat"));
	xRegisterFunction("int xJoyXDir(int)", xGetFunctionAddress("xJoyXDir"));
	xRegisterFunction("int xJoyYDir(int)", xGetFunctionAddress("xJoyYDir"));
	xRegisterFunction("int xJoyZDir(int)", xGetFunctionAddress("xJoyZDir"));
	xRegisterFunction("int xJoyUDir(int)", xGetFunctionAddress("xJoyUDir"));
	xRegisterFunction("int xJoyVDir(int)", xGetFunctionAddress("xJoyVDir"));
	xRegisterFunction("int xCreateLight(int)", xGetFunctionAddress("xCreateLight"));
	xRegisterFunction("void xLightShadowEpsilons(int, float, float)", xGetFunctionAddress("xLightShadowEpsilons"));
	xRegisterFunction("void xLightEnableShadows(int, int)", xGetFunctionAddress("xLightEnableShadows"));
	xRegisterFunction("int xLightShadowsEnabled(int)", xGetFunctionAddress("xLightShadowsEnabled"));
	xRegisterFunction("void xLightRange(int, float)", xGetFunctionAddress("xLightRange"));
	xRegisterFunction("void xLightColor(int, int, int, int)", xGetFunctionAddress("xLightColor"));
	xRegisterFunction("void xLightConeAngles(int, float, float)", xGetFunctionAddress("xLightConeAngles"));
	xRegisterFunction("int xCreateLog(int, int, charsArray, charsArray)", xGetFunctionAddress("xCreateLog"));
	xRegisterFunction("int xCloseLog()", xGetFunctionAddress("xCloseLog"));
	xRegisterFunction("charsArray xGetLogString()", xGetFunctionAddress("xGetLogString"));
	xRegisterFunction("void xClearLogString()", xGetFunctionAddress("xClearLogString"));
	xRegisterFunction("void xSetLogLevel(int)", xGetFunctionAddress("xSetLogLevel"));
	xRegisterFunction("void xSetLogTarget(int)", xGetFunctionAddress("xSetLogTarget"));
	xRegisterFunction("int xGetLogLevel()", xGetFunctionAddress("xGetLogLevel"));
	xRegisterFunction("int xGetLogTarget()", xGetFunctionAddress("xGetLogTarget"));
	xRegisterFunction("void xLogInfo(charsArray, charsArray, charsArray, int)", xGetFunctionAddress("xLogInfo"));
	xRegisterFunction("void xLogMessage(charsArray, charsArray, charsArray, int)", xGetFunctionAddress("xLogMessage"));
	xRegisterFunction("void xLogWarning(charsArray, charsArray, charsArray, int)", xGetFunctionAddress("xLogWarning"));
	xRegisterFunction("void xLogError(charsArray, charsArray, charsArray, int)", xGetFunctionAddress("xLogError"));
	xRegisterFunction("void xLogFatal(charsArray, charsArray, charsArray, int)", xGetFunctionAddress("xLogFatal"));
	xRegisterFunction("int xCreateMesh(int)", xGetFunctionAddress("xCreateMesh"));
	xRegisterFunction("int xLoadMesh(charsArray, int)", xGetFunctionAddress("xLoadMesh"));
	xRegisterFunction("int xLoadMeshWithChild(charsArray, int)", xGetFunctionAddress("xLoadMeshWithChild"));
	xRegisterFunction("int xLoadAnimMesh(charsArray, int)", xGetFunctionAddress("xLoadAnimMesh"));
	xRegisterFunction("int xCreateCube(int)", xGetFunctionAddress("xCreateCube"));
	xRegisterFunction("int xCreateSphere(int, int)", xGetFunctionAddress("xCreateSphere"));
	xRegisterFunction("int xCreateCylinder(int, int, int)", xGetFunctionAddress("xCreateCylinder"));
	xRegisterFunction("int xCreateTorus(int, float, float, int)", xGetFunctionAddress("xCreateTorus"));
	xRegisterFunction("int xCreateCone(int, int, int)", xGetFunctionAddress("xCreateCone"));
	xRegisterFunction("int xCopyMesh(int, int)", xGetFunctionAddress("xCopyMesh"));
	xRegisterFunction("void xAddMesh(int, int)", xGetFunctionAddress("xAddMesh"));
	xRegisterFunction("void xFlipMesh(int)", xGetFunctionAddress("xFlipMesh"));
	xRegisterFunction("void xPaintMesh(int, int)", xGetFunctionAddress("xPaintMesh"));
	xRegisterFunction("void xFitMesh(int, float, float, float, float, float, float, int)", xGetFunctionAddress("xFitMesh"));
	xRegisterFunction("float xMeshWidth(int, int)", xGetFunctionAddress("xMeshWidth"));
	xRegisterFunction("float xMeshHeight(int, int)", xGetFunctionAddress("xMeshHeight"));
	xRegisterFunction("float xMeshDepth(int, int)", xGetFunctionAddress("xMeshDepth"));
	xRegisterFunction("void xScaleMesh(int, float, float, float)", xGetFunctionAddress("xScaleMesh"));
	xRegisterFunction("void xRotateMesh(int, float, float, float)", xGetFunctionAddress("xRotateMesh"));
	xRegisterFunction("void xPositionMesh(int, float, float, float)", xGetFunctionAddress("xPositionMesh"));
	xRegisterFunction("void xUpdateNormals(int)", xGetFunctionAddress("xUpdateNormals"));
	xRegisterFunction("void xUpdateN(int)", xGetFunctionAddress("xUpdateN"));
	xRegisterFunction("void xUpdateTB(int)", xGetFunctionAddress("xUpdateTB"));
	xRegisterFunction("int xMeshesBBIntersect(int, int)", xGetFunctionAddress("xMeshesBBIntersect"));
	xRegisterFunction("int xMeshesIntersect(int, int)", xGetFunctionAddress("xMeshesIntersect"));
	xRegisterFunction("int xGetMeshVB(int)", xGetFunctionAddress("xGetMeshVB"));
	xRegisterFunction("int xGetMeshIB(int)", xGetFunctionAddress("xGetMeshIB"));
	xRegisterFunction("int xGetMeshVBSize(int)", xGetFunctionAddress("xGetMeshVBSize"));
	xRegisterFunction("int xGetMeshIBSize(int)", xGetFunctionAddress("xGetMeshIBSize"));
	xRegisterFunction("void xDeleteMeshVB(int)", xGetFunctionAddress("xDeleteMeshVB"));
	xRegisterFunction("void xDeleteMeshIB(int)", xGetFunctionAddress("xDeleteMeshIB"));
	xRegisterFunction("int xCountSurfaces(int)", xGetFunctionAddress("xCountSurfaces"));
	xRegisterFunction("int xGetSurface(int, int)", xGetFunctionAddress("xGetSurface"));
	xRegisterFunction("int xCreatePivot(int)", xGetFunctionAddress("xCreatePivot"));
	xRegisterFunction("int xFindSurface(int, int)", xGetFunctionAddress("xFindSurface"));
	xRegisterFunction("int xCreatePoly(int, int)", xGetFunctionAddress("xCreatePoly"));
	xRegisterFunction("void xMeshSingleSurface(int)", xGetFunctionAddress("xMeshSingleSurface"));
	xRegisterFunction("int xSaveMesh(int, charsArray)", xGetFunctionAddress("xSaveMesh"));
	xRegisterFunction("void xLightMesh(int, int, int, int, float, float, float, float)", xGetFunctionAddress("xLightMesh"));
	xRegisterFunction("void xMeshPrimitiveType(int, int)", xGetFunctionAddress("xMeshPrimitiveType"));
	xRegisterFunction("void xParticlePosition(int, float, float, float)", xGetFunctionAddress("xParticlePosition"));
	xRegisterFunction("float xParticleX(int)", xGetFunctionAddress("xParticleX"));
	xRegisterFunction("float xParticleY(int)", xGetFunctionAddress("xParticleY"));
	xRegisterFunction("float xParticleZ(int)", xGetFunctionAddress("xParticleZ"));
	xRegisterFunction("void xParticleVeclocity(int, float, float, float)", xGetFunctionAddress("xParticleVeclocity"));
	xRegisterFunction("float xParticleVX(int)", xGetFunctionAddress("xParticleVX"));
	xRegisterFunction("float xParticleVY(int)", xGetFunctionAddress("xParticleVY"));
	xRegisterFunction("float xParticleVZ(int)", xGetFunctionAddress("xParticleVZ"));
	xRegisterFunction("void xParticleRotation(int, float, float, float)", xGetFunctionAddress("xParticleRotation"));
	xRegisterFunction("float xParticlePitch(int)", xGetFunctionAddress("xParticlePitch"));
	xRegisterFunction("float xParticleYaw(int)", xGetFunctionAddress("xParticleYaw"));
	xRegisterFunction("float xParticleRoll(int)", xGetFunctionAddress("xParticleRoll"));
	xRegisterFunction("void xParticleTorque(int, float, float, float)", xGetFunctionAddress("xParticleTorque"));
	xRegisterFunction("float xParticleTPitch(int)", xGetFunctionAddress("xParticleTPitch"));
	xRegisterFunction("float xParticleTYaw(int)", xGetFunctionAddress("xParticleTYaw"));
	xRegisterFunction("float xParticleTRoll(int)", xGetFunctionAddress("xParticleTRoll"));
	xRegisterFunction("void xParticleSetAlpha(int, float)", xGetFunctionAddress("xParticleSetAlpha"));
	xRegisterFunction("float xParticleGetAlpha(int)", xGetFunctionAddress("xParticleGetAlpha"));
	xRegisterFunction("void xParticleColor(int, float, float, float)", xGetFunctionAddress("xParticleColor"));
	xRegisterFunction("float xParticleRed(int)", xGetFunctionAddress("xParticleRed"));
	xRegisterFunction("float xParticleGreen(int)", xGetFunctionAddress("xParticleGreen"));
	xRegisterFunction("float xParticleBlue(int)", xGetFunctionAddress("xParticleBlue"));
	xRegisterFunction("void xParticleScale(int, float, float)", xGetFunctionAddress("xParticleScale"));
	xRegisterFunction("float xParticleSX(int)", xGetFunctionAddress("xParticleSX"));
	xRegisterFunction("float xParticleSY(int)", xGetFunctionAddress("xParticleSY"));
	xRegisterFunction("void xParticleScaleSpeed(int, float, float)", xGetFunctionAddress("xParticleScaleSpeed"));
	xRegisterFunction("float xParticleScaleSpeedX(int)", xGetFunctionAddress("xParticleScaleSpeedX"));
	xRegisterFunction("float xParticleScaleSpeedY(int)", xGetFunctionAddress("xParticleScaleSpeedY"));
	xRegisterFunction("void xEntityAddDummyShape(int)", xGetFunctionAddress("xEntityAddDummyShape"));
	xRegisterFunction("void xEntityAddBoxShape(int, float, float, float, float)", xGetFunctionAddress("xEntityAddBoxShape"));
	xRegisterFunction("void xEntityAddSphereShape(int, float, float)", xGetFunctionAddress("xEntityAddSphereShape"));
	xRegisterFunction("void xEntityAddCapsuleShape(int, float, float, float)", xGetFunctionAddress("xEntityAddCapsuleShape"));
	xRegisterFunction("void xEntityAddConeShape(int, float, float, float)", xGetFunctionAddress("xEntityAddConeShape"));
	xRegisterFunction("void xEntityAddCylinderShape(int, float, float, float, float)", xGetFunctionAddress("xEntityAddCylinderShape"));
	xRegisterFunction("void xEntityAddTriMeshShape(int, float)", xGetFunctionAddress("xEntityAddTriMeshShape"));
	xRegisterFunction("void xEntityAddHullShape(int, float)", xGetFunctionAddress("xEntityAddHullShape"));
	xRegisterFunction("void xWorldGravity(float, float, float, int)", xGetFunctionAddress("xWorldGravity"));
	xRegisterFunction("float xWorldGravityX(int)", xGetFunctionAddress("xWorldGravityX"));
	xRegisterFunction("float xWorldGravityY(int)", xGetFunctionAddress("xWorldGravityY"));
	xRegisterFunction("float xWorldGravityZ(int)", xGetFunctionAddress("xWorldGravityZ"));
	xRegisterFunction("void xWorldFrequency(float, int)", xGetFunctionAddress("xWorldFrequency"));
	xRegisterFunction("void xEntityApplyCentralForce(int, float, float, float)", xGetFunctionAddress("xEntityApplyCentralForce"));
	xRegisterFunction("void xEntityApplyCentralImpulse(int, float, float, float)", xGetFunctionAddress("xEntityApplyCentralImpulse"));
	xRegisterFunction("void xEntityApplyTorque(int, float, float, float)", xGetFunctionAddress("xEntityApplyTorque"));
	xRegisterFunction("void xEntityApplyTorqueImpulse(int, float, float, float)", xGetFunctionAddress("xEntityApplyTorqueImpulse"));
	xRegisterFunction("void xEntityApplyForce(int, float, float, float, float, float, float)", xGetFunctionAddress("xEntityApplyForce"));
	xRegisterFunction("void xEntityApplyImpulse(int, float, float, float, float, float, float)", xGetFunctionAddress("xEntityApplyImpulse"));
	xRegisterFunction("void xEntityReleaseForces(int)", xGetFunctionAddress("xEntityReleaseForces"));
	xRegisterFunction("void xEntityDamping(int, float, float)", xGetFunctionAddress("xEntityDamping"));
	xRegisterFunction("float xGetEntityLinearDamping(int)", xGetFunctionAddress("xGetEntityLinearDamping"));
	xRegisterFunction("float xGetEntityAngularDamping(int)", xGetFunctionAddress("xGetEntityAngularDamping"));
	xRegisterFunction("void xEntityFriction(int, float)", xGetFunctionAddress("xEntityFriction"));
	xRegisterFunction("float xGetEntityFriction(int)", xGetFunctionAddress("xGetEntityFriction"));
	xRegisterFunction("float xEntityForceX(int)", xGetFunctionAddress("xEntityForceX"));
	xRegisterFunction("float xEntityForceY(int)", xGetFunctionAddress("xEntityForceY"));
	xRegisterFunction("float xEntityForceZ(int)", xGetFunctionAddress("xEntityForceZ"));
	xRegisterFunction("float xEntityTorqueX(int)", xGetFunctionAddress("xEntityTorqueX"));
	xRegisterFunction("float xEntityTorqueY(int)", xGetFunctionAddress("xEntityTorqueY"));
	xRegisterFunction("float xEntityTorqueZ(int)", xGetFunctionAddress("xEntityTorqueZ"));
	xRegisterFunction("void xFreeEntityShapes(int)", xGetFunctionAddress("xFreeEntityShapes"));
	xRegisterFunction("int xCountContacts(int)", xGetFunctionAddress("xCountContacts"));
	xRegisterFunction("float xEntityContactX(int, int)", xGetFunctionAddress("xEntityContactX"));
	xRegisterFunction("float xEntityContactY(int, int)", xGetFunctionAddress("xEntityContactY"));
	xRegisterFunction("float xEntityContactZ(int, int)", xGetFunctionAddress("xEntityContactZ"));
	xRegisterFunction("float xEntityContactNX(int, int)", xGetFunctionAddress("xEntityContactNX"));
	xRegisterFunction("float xEntityContactNY(int, int)", xGetFunctionAddress("xEntityContactNY"));
	xRegisterFunction("float xEntityContactNZ(int, int)", xGetFunctionAddress("xEntityContactNZ"));
	xRegisterFunction("float xEntityContactDistance(int, int)", xGetFunctionAddress("xEntityContactDistance"));
	xRegisterFunction("int xContactEntity(int, int)", xGetFunctionAddress("xContactEntity"));
	xRegisterFunction("int xCreateJoint(int, int, int)", xGetFunctionAddress("xCreateJoint"));
	xRegisterFunction("void xFreeJoint(int)", xGetFunctionAddress("xFreeJoint"));
	xRegisterFunction("void xJointPivotA(int, float, float, float)", xGetFunctionAddress("xJointPivotA"));
	xRegisterFunction("void xJointPivotB(int, float, float, float)", xGetFunctionAddress("xJointPivotB"));
	xRegisterFunction("float xJointPivotAX(int)", xGetFunctionAddress("xJointPivotAX"));
	xRegisterFunction("float xJointPivotAY(int)", xGetFunctionAddress("xJointPivotAY"));
	xRegisterFunction("float xJointPivotAZ(int)", xGetFunctionAddress("xJointPivotAZ"));
	xRegisterFunction("float xJointPivotBX(int)", xGetFunctionAddress("xJointPivotBX"));
	xRegisterFunction("float xJointPivotBY(int)", xGetFunctionAddress("xJointPivotBY"));
	xRegisterFunction("float xJointPivotBZ(int)", xGetFunctionAddress("xJointPivotBZ"));
	xRegisterFunction("void xJointLinearLimits(int, float, float, float, float, float, float)", xGetFunctionAddress("xJointLinearLimits"));
	xRegisterFunction("void xJointAngularLimits(int, float, float, float, float, float, float)", xGetFunctionAddress("xJointAngularLimits"));
	xRegisterFunction("float xJointLinearLowerX(int)", xGetFunctionAddress("xJointLinearLowerX"));
	xRegisterFunction("float xJointLinearLowerY(int)", xGetFunctionAddress("xJointLinearLowerY"));
	xRegisterFunction("float xJointLinearLowerZ(int)", xGetFunctionAddress("xJointLinearLowerZ"));
	xRegisterFunction("float xJointLinearUpperX(int)", xGetFunctionAddress("xJointLinearUpperX"));
	xRegisterFunction("float xJointLinearUpperY(int)", xGetFunctionAddress("xJointLinearUpperY"));
	xRegisterFunction("float xJointLinearUpperZ(int)", xGetFunctionAddress("xJointLinearUpperZ"));
	xRegisterFunction("float xJointAngularLowerX(int)", xGetFunctionAddress("xJointAngularLowerX"));
	xRegisterFunction("float xJointAngularLowerY(int)", xGetFunctionAddress("xJointAngularLowerY"));
	xRegisterFunction("float xJointAngularLowerZ(int)", xGetFunctionAddress("xJointAngularLowerZ"));
	xRegisterFunction("float xJointAngularUpperX(int)", xGetFunctionAddress("xJointAngularUpperX"));
	xRegisterFunction("float xJointAngularUpperY(int)", xGetFunctionAddress("xJointAngularUpperY"));
	xRegisterFunction("float xJointAngularUpperZ(int)", xGetFunctionAddress("xJointAngularUpperZ"));
	xRegisterFunction("void xJoint6dofSpringParam(int, int, int, float, float)", xGetFunctionAddress("xJoint6dofSpringParam"));
	xRegisterFunction("void xJointHingeAxis(int, float, float, float)", xGetFunctionAddress("xJointHingeAxis"));
	xRegisterFunction("void xJointHingeLimit(int, float, float, float, float, float)", xGetFunctionAddress("xJointHingeLimit"));
	xRegisterFunction("float xJointHingeLowerLimit(int)", xGetFunctionAddress("xJointHingeLowerLimit"));
	xRegisterFunction("float xJointHingeUpperLimit(int)", xGetFunctionAddress("xJointHingeUpperLimit"));
	xRegisterFunction("void xJointEnableMotor(int, int, float, float, int)", xGetFunctionAddress("xJointEnableMotor"));
	xRegisterFunction("void xJointHingeMotorTarget(int, float, float)", xGetFunctionAddress("xJointHingeMotorTarget"));
	xRegisterFunction("void xEntityLinearFactor(int, float, float, float)", xGetFunctionAddress("xEntityLinearFactor"));
	xRegisterFunction("float xEntityLinearFactorX(int)", xGetFunctionAddress("xEntityLinearFactorX"));
	xRegisterFunction("float xEntityLinearFactorY(int)", xGetFunctionAddress("xEntityLinearFactorY"));
	xRegisterFunction("float xEntityLinearFactorZ(int)", xGetFunctionAddress("xEntityLinearFactorZ"));
	xRegisterFunction("void xEntityAngularFactor(int, float, float, float)", xGetFunctionAddress("xEntityAngularFactor"));
	xRegisterFunction("float xEntityAngularFactorX(int)", xGetFunctionAddress("xEntityAngularFactorX"));
	xRegisterFunction("float xEntityAngularFactorY(int)", xGetFunctionAddress("xEntityAngularFactorY"));
	xRegisterFunction("float xEntityAngularFactorZ(int)", xGetFunctionAddress("xEntityAngularFactorZ"));
	xRegisterFunction("void xEntityGravity(int, float, float, float)", xGetFunctionAddress("xEntityGravity"));
	xRegisterFunction("float xEntityGravityX(int)", xGetFunctionAddress("xEntityGravityX"));
	xRegisterFunction("float xEntityGravityY(int)", xGetFunctionAddress("xEntityGravityY"));
	xRegisterFunction("float xEntityGravityZ(int)", xGetFunctionAddress("xEntityGravityZ"));
	xRegisterFunction("void xPhysicsDebugRender(int)", xGetFunctionAddress("xPhysicsDebugRender"));
	xRegisterFunction("int xLoadPostEffect(charsArray)", xGetFunctionAddress("xLoadPostEffect"));
	xRegisterFunction("void xFreePostEffect(int)", xGetFunctionAddress("xFreePostEffect"));
	xRegisterFunction("void xSetPostEffect(int, int, charsArray)", xGetFunctionAddress("xSetPostEffect"));
	xRegisterFunction("void xRenderPostEffects()", xGetFunctionAddress("xRenderPostEffects"));
	xRegisterFunction("void xSetPostEffectInt(int, charsArray, int)", xGetFunctionAddress("xSetPostEffectInt"));
	xRegisterFunction("void xSetPostEffectFloat(int, charsArray, float)", xGetFunctionAddress("xSetPostEffectFloat"));
	xRegisterFunction("void xSetPostEffectBool(int, charsArray, int)", xGetFunctionAddress("xSetPostEffectBool"));
	xRegisterFunction("void xSetPostEffectVector(int, charsArray, float, float, float, float)", xGetFunctionAddress("xSetPostEffectVector"));
	xRegisterFunction("void xSetPostEffectTexture(int, charsArray, int, int)", xGetFunctionAddress("xSetPostEffectTexture"));
	xRegisterFunction("void xDeletePostEffectConstant(int, charsArray)", xGetFunctionAddress("xDeletePostEffectConstant"));
	xRegisterFunction("void xClearPostEffectConstants(int)", xGetFunctionAddress("xClearPostEffectConstants"));
	xRegisterFunction("int xCreatePSystem(int)", xGetFunctionAddress("xCreatePSystem"));
	xRegisterFunction("int xPSystemType(int)", xGetFunctionAddress("xPSystemType"));
	xRegisterFunction("void xPSystemSetBlend(int, int)", xGetFunctionAddress("xPSystemSetBlend"));
	xRegisterFunction("int xPSystemGetBlend(int)", xGetFunctionAddress("xPSystemGetBlend"));
	xRegisterFunction("void xPSystemSetMaxParticles(int, int)", xGetFunctionAddress("xPSystemSetMaxParticles"));
	xRegisterFunction("int xPSystemGetMaxParticles(int)", xGetFunctionAddress("xPSystemGetMaxParticles"));
	xRegisterFunction("void xPSystemSetEmitterLifetime(int, int)", xGetFunctionAddress("xPSystemSetEmitterLifetime"));
	xRegisterFunction("int xPSystemGetEmitterLifetime(int)", xGetFunctionAddress("xPSystemGetEmitterLifetime"));
	xRegisterFunction("void xPSystemSetParticleLifetime(int, int)", xGetFunctionAddress("xPSystemSetParticleLifetime"));
	xRegisterFunction("int xPSystemGetParticleLifetime(int)", xGetFunctionAddress("xPSystemGetParticleLifetime"));
	xRegisterFunction("void xPSystemSetCreationInterval(int, int)", xGetFunctionAddress("xPSystemSetCreationInterval"));
	xRegisterFunction("int xPSystemGetCreationInterval(int)", xGetFunctionAddress("xPSystemGetCreationInterval"));
	xRegisterFunction("void xPSystemSetCreationFrequency(int, int)", xGetFunctionAddress("xPSystemSetCreationFrequency"));
	xRegisterFunction("int xPSystemGetCreationFrequency(int)", xGetFunctionAddress("xPSystemGetCreationFrequency"));
	xRegisterFunction("void xPSystemSetTexture(int, int, int, float)", xGetFunctionAddress("xPSystemSetTexture"));
	xRegisterFunction("int xPSystemGetTexture(int)", xGetFunctionAddress("xPSystemGetTexture"));
	xRegisterFunction("int xPSystemGetTextureFrames(int)", xGetFunctionAddress("xPSystemGetTextureFrames"));
	xRegisterFunction("int xPSystemGetTextureAnimationSpeed(int)", xGetFunctionAddress("xPSystemGetTextureAnimationSpeed"));
	xRegisterFunction("void xPSystemSetOffset(int, float, float, float, float, float, float)", xGetFunctionAddress("xPSystemSetOffset"));
	xRegisterFunction("float xPSystemGetOffsetMinX(int)", xGetFunctionAddress("xPSystemGetOffsetMinX"));
	xRegisterFunction("float xPSystemGetOffsetMinY(int)", xGetFunctionAddress("xPSystemGetOffsetMinY"));
	xRegisterFunction("float xPSystemGetOffsetMinZ(int)", xGetFunctionAddress("xPSystemGetOffsetMinZ"));
	xRegisterFunction("float xPSystemGetOffsetMaxX(int)", xGetFunctionAddress("xPSystemGetOffsetMaxX"));
	xRegisterFunction("float xPSystemGetOffsetMaxY(int)", xGetFunctionAddress("xPSystemGetOffsetMaxY"));
	xRegisterFunction("float xPSystemGetOffsetMaxZ(int)", xGetFunctionAddress("xPSystemGetOffsetMaxZ"));
	xRegisterFunction("void xPSystemSetVelocity(int, float, float, float, float, float, float)", xGetFunctionAddress("xPSystemSetVelocity"));
	xRegisterFunction("float xPSystemGetVelocityMinX(int)", xGetFunctionAddress("xPSystemGetVelocityMinX"));
	xRegisterFunction("float xPSystemGetVelocityMinY(int)", xGetFunctionAddress("xPSystemGetVelocityMinY"));
	xRegisterFunction("float xPSystemGetVelocityMinZ(int)", xGetFunctionAddress("xPSystemGetVelocityMinZ"));
	xRegisterFunction("float xPSystemGetVelocityMaxX(int)", xGetFunctionAddress("xPSystemGetVelocityMaxX"));
	xRegisterFunction("float xPSystemGetVelocityMaxY(int)", xGetFunctionAddress("xPSystemGetVelocityMaxY"));
	xRegisterFunction("float xPSystemGetVelocityMaxZ(int)", xGetFunctionAddress("xPSystemGetVelocityMaxZ"));
	xRegisterFunction("void xPSystemEnableFixedQuads(int, int)", xGetFunctionAddress("xPSystemEnableFixedQuads"));
	xRegisterFunction("int xPSystemFixedQuadsUsed(int)", xGetFunctionAddress("xPSystemFixedQuadsUsed"));
	xRegisterFunction("void xPSystemSetTorque(int, float, float, float, float, float, float)", xGetFunctionAddress("xPSystemSetTorque"));
	xRegisterFunction("float xPSystemGetTorqueMinX(int)", xGetFunctionAddress("xPSystemGetTorqueMinX"));
	xRegisterFunction("float xPSystemGetTorqueMinY(int)", xGetFunctionAddress("xPSystemGetTorqueMinY"));
	xRegisterFunction("float xPSystemGetTorqueMinZ(int)", xGetFunctionAddress("xPSystemGetTorqueMinZ"));
	xRegisterFunction("float xPSystemGetTorqueMaxX(int)", xGetFunctionAddress("xPSystemGetTorqueMaxX"));
	xRegisterFunction("float xPSystemGetTorqueMaxY(int)", xGetFunctionAddress("xPSystemGetTorqueMaxY"));
	xRegisterFunction("float xPSystemGetTorqueMaxZ(int)", xGetFunctionAddress("xPSystemGetTorqueMaxZ"));
	xRegisterFunction("void xPSystemSetGravity(int, float)", xGetFunctionAddress("xPSystemSetGravity"));
	xRegisterFunction("float xPSystemGetGravity(int)", xGetFunctionAddress("xPSystemGetGravity"));
	xRegisterFunction("void xPSystemSetAlpha(int, float)", xGetFunctionAddress("xPSystemSetAlpha"));
	xRegisterFunction("float xPSystemGetAlpha(int)", xGetFunctionAddress("xPSystemGetAlpha"));
	xRegisterFunction("void xPSystemSetFadeSpeed(int, float)", xGetFunctionAddress("xPSystemSetFadeSpeed"));
	xRegisterFunction("float xPSystemGetFadeSpeed(int)", xGetFunctionAddress("xPSystemGetFadeSpeed"));
	xRegisterFunction("void xPSystemSetParticleSize(int, float, float, float, float)", xGetFunctionAddress("xPSystemSetParticleSize"));
	xRegisterFunction("float xPSystemGetSizeMinX(int)", xGetFunctionAddress("xPSystemGetSizeMinX"));
	xRegisterFunction("float xPSystemGetSizeMinY(int)", xGetFunctionAddress("xPSystemGetSizeMinY"));
	xRegisterFunction("float xPSystemGetSizeMaxX(int)", xGetFunctionAddress("xPSystemGetSizeMaxX"));
	xRegisterFunction("float xPSystemGetSizeMaxY(int)", xGetFunctionAddress("xPSystemGetSizeMaxY"));
	xRegisterFunction("void xPSystemSetScaleSpeed(int, float, float, float, float)", xGetFunctionAddress("xPSystemSetScaleSpeed"));
	xRegisterFunction("float xPSystemGetScaleSpeedMinX(int)", xGetFunctionAddress("xPSystemGetScaleSpeedMinX"));
	xRegisterFunction("float xPSystemGetScaleSpeedMinY(int)", xGetFunctionAddress("xPSystemGetScaleSpeedMinY"));
	xRegisterFunction("float xPSystemGetScaleSpeedMaxX(int)", xGetFunctionAddress("xPSystemGetScaleSpeedMaxX"));
	xRegisterFunction("float xPSystemGetScaleSpeedMaxY(int)", xGetFunctionAddress("xPSystemGetScaleSpeedMaxY"));
	xRegisterFunction("void xPSystemSetAngles(int, float, float, float, float, float, float)", xGetFunctionAddress("xPSystemSetAngles"));
	xRegisterFunction("float xPSystemGetAnglesMinX(int)", xGetFunctionAddress("xPSystemGetAnglesMinX"));
	xRegisterFunction("float xPSystemGetAnglesMinY(int)", xGetFunctionAddress("xPSystemGetAnglesMinY"));
	xRegisterFunction("float xPSystemGetAnglesMinZ(int)", xGetFunctionAddress("xPSystemGetAnglesMinZ"));
	xRegisterFunction("float xPSystemGetAnglesMaxX(int)", xGetFunctionAddress("xPSystemGetAnglesMaxX"));
	xRegisterFunction("float xPSystemGetAnglesMaxY(int)", xGetFunctionAddress("xPSystemGetAnglesMaxY"));
	xRegisterFunction("float xPSystemGetAnglesMaxZ(int)", xGetFunctionAddress("xPSystemGetAnglesMaxZ"));
	xRegisterFunction("void xPSystemSetColorMode(int, int)", xGetFunctionAddress("xPSystemSetColorMode"));
	xRegisterFunction("int xPSystemGetColorMode(int)", xGetFunctionAddress("xPSystemGetColorMode"));
	xRegisterFunction("void xPSystemSetColors(int, float, float, float, float, float, float)", xGetFunctionAddress("xPSystemSetColors"));
	xRegisterFunction("float xPSystemGetBeginColorRed(int)", xGetFunctionAddress("xPSystemGetBeginColorRed"));
	xRegisterFunction("float xPSystemGetBeginColorGreen(int)", xGetFunctionAddress("xPSystemGetBeginColorGreen"));
	xRegisterFunction("float xPSystemGetBeginColorBlue(int)", xGetFunctionAddress("xPSystemGetBeginColorBlue"));
	xRegisterFunction("float xPSystemGetEndColorRed(int)", xGetFunctionAddress("xPSystemGetEndColorRed"));
	xRegisterFunction("float xPSystemGetEndColorGreen(int)", xGetFunctionAddress("xPSystemGetEndColorGreen"));
	xRegisterFunction("float xPSystemGetEndColorBlue(int)", xGetFunctionAddress("xPSystemGetEndColorBlue"));
	xRegisterFunction("void xFreePSystem(int)", xGetFunctionAddress("xFreePSystem"));
	xRegisterFunction("void xPSystemSetParticleParenting(int, int)", xGetFunctionAddress("xPSystemSetParticleParenting"));
	xRegisterFunction("int xPSystemGetParticleParenting(int)", xGetFunctionAddress("xPSystemGetParticleParenting"));
	xRegisterFunction("int xLinePick(float, float, float, float, float, float, float)", xGetFunctionAddress("xLinePick"));
	xRegisterFunction("int xEntityPick(int, float)", xGetFunctionAddress("xEntityPick"));
	xRegisterFunction("int xCameraPick(int, int, int)", xGetFunctionAddress("xCameraPick"));
	xRegisterFunction("float xPickedNX()", xGetFunctionAddress("xPickedNX"));
	xRegisterFunction("float xPickedNY()", xGetFunctionAddress("xPickedNY"));
	xRegisterFunction("float xPickedNZ()", xGetFunctionAddress("xPickedNZ"));
	xRegisterFunction("float xPickedX()", xGetFunctionAddress("xPickedX"));
	xRegisterFunction("float xPickedY()", xGetFunctionAddress("xPickedY"));
	xRegisterFunction("float xPickedZ()", xGetFunctionAddress("xPickedZ"));
	xRegisterFunction("int xPickedEntity()", xGetFunctionAddress("xPickedEntity"));
	xRegisterFunction("int xPickedSurface()", xGetFunctionAddress("xPickedSurface"));
	xRegisterFunction("int xPickedTriangle()", xGetFunctionAddress("xPickedTriangle"));
	xRegisterFunction("int xPickedTime()", xGetFunctionAddress("xPickedTime"));
	xRegisterFunction("void xSetShadowsBlur(int)", xGetFunctionAddress("xSetShadowsBlur"));
	xRegisterFunction("void xSetShadowShader(charsArray)", xGetFunctionAddress("xSetShadowShader"));
	xRegisterFunction("int xInitShadows(int, int, int)", xGetFunctionAddress("xInitShadows"));
	xRegisterFunction("void xSetShadowParams(int, float, int, float)", xGetFunctionAddress("xSetShadowParams"));
	xRegisterFunction("void xRenderShadows(int, int)", xGetFunctionAddress("xRenderShadows"));
	xRegisterFunction("void xShadowPriority(int)", xGetFunctionAddress("xShadowPriority"));
	xRegisterFunction("void xCameraDisableShadows(int)", xGetFunctionAddress("xCameraDisableShadows"));
	xRegisterFunction("void xCameraEnableShadows(int)", xGetFunctionAddress("xCameraEnableShadows"));
	xRegisterFunction("void xEntityCastShadows(int, int, int)", xGetFunctionAddress("xEntityCastShadows"));
	xRegisterFunction("void xEntityReceiveShadows(int, int, int)", xGetFunctionAddress("xEntityReceiveShadows"));
	xRegisterFunction("int xEntityIsCaster(int, int)", xGetFunctionAddress("xEntityIsCaster"));
	xRegisterFunction("int xEntityIsReceiver(int, int)", xGetFunctionAddress("xEntityIsReceiver"));
	xRegisterFunction("int xLoadSound(charsArray)", xGetFunctionAddress("xLoadSound"));
	xRegisterFunction("int xLoad3DSound(charsArray)", xGetFunctionAddress("xLoad3DSound"));
	xRegisterFunction("void xFreeSound(int)", xGetFunctionAddress("xFreeSound"));
	xRegisterFunction("void xLoopSound(int)", xGetFunctionAddress("xLoopSound"));
	xRegisterFunction("void xSoundPitch(int, int)", xGetFunctionAddress("xSoundPitch"));
	xRegisterFunction("void xSoundVolume(int, float)", xGetFunctionAddress("xSoundVolume"));
	xRegisterFunction("void xSoundPan(int, float)", xGetFunctionAddress("xSoundPan"));
	xRegisterFunction("int xPlaySound(int)", xGetFunctionAddress("xPlaySound"));
	xRegisterFunction("void xStopChannel(int)", xGetFunctionAddress("xStopChannel"));
	xRegisterFunction("void xPauseChannel(int)", xGetFunctionAddress("xPauseChannel"));
	xRegisterFunction("void xResumeChannel(int)", xGetFunctionAddress("xResumeChannel"));
	xRegisterFunction("int xPlayMusic(charsArray)", xGetFunctionAddress("xPlayMusic"));
	xRegisterFunction("void xChannelPitch(int, int)", xGetFunctionAddress("xChannelPitch"));
	xRegisterFunction("void xChannelVolume(int, float)", xGetFunctionAddress("xChannelVolume"));
	xRegisterFunction("void xChannelPan(int, float)", xGetFunctionAddress("xChannelPan"));
	xRegisterFunction("int xChannelPlaying(int)", xGetFunctionAddress("xChannelPlaying"));
	xRegisterFunction("int xEmitSound(int, int)", xGetFunctionAddress("xEmitSound"));
	xRegisterFunction("int xCreateListener(int, float, float, float)", xGetFunctionAddress("xCreateListener"));
	xRegisterFunction("int xGetListener()", xGetFunctionAddress("xGetListener"));
	xRegisterFunction("int xInitalizeSound()", xGetFunctionAddress("xInitalizeSound"));
	xRegisterFunction("int xCreateSprite(int)", xGetFunctionAddress("xCreateSprite"));
	xRegisterFunction("void xSpriteViewMode(int, int)", xGetFunctionAddress("xSpriteViewMode"));
	xRegisterFunction("void xHandleSprite(int, float, float)", xGetFunctionAddress("xHandleSprite"));
	xRegisterFunction("int xLoadSprite(charsArray, int, int)", xGetFunctionAddress("xLoadSprite"));
	xRegisterFunction("void xRotateSprite(int, float)", xGetFunctionAddress("xRotateSprite"));
	xRegisterFunction("void xScaleSprite(int, float, float)", xGetFunctionAddress("xScaleSprite"));
	xRegisterFunction("int xCreateSurface(int, int, int)", xGetFunctionAddress("xCreateSurface"));
	xRegisterFunction("int xGetSurfaceBrush(int)", xGetFunctionAddress("xGetSurfaceBrush"));
	xRegisterFunction("int xAddVertex(int, float, float, float, float, float, float)", xGetFunctionAddress("xAddVertex"));
	xRegisterFunction("int xAddTriangle(int, int, int, int)", xGetFunctionAddress("xAddTriangle"));
	xRegisterFunction("void xSetSurfaceFrustumSphere(int, float, float, float, float)", xGetFunctionAddress("xSetSurfaceFrustumSphere"));
	xRegisterFunction("void xVertexCoords(int, int, float, float, float)", xGetFunctionAddress("xVertexCoords"));
	xRegisterFunction("void xVertexNormal(int, int, float, float, float)", xGetFunctionAddress("xVertexNormal"));
	xRegisterFunction("void xVertexTangent(int, int, float, float, float)", xGetFunctionAddress("xVertexTangent"));
	xRegisterFunction("void xVertexBinormal(int, int, float, float, float)", xGetFunctionAddress("xVertexBinormal"));
	xRegisterFunction("void xVertexColor(int, int, int, int, int, float)", xGetFunctionAddress("xVertexColor"));
	xRegisterFunction("void xVertexTexCoords(int, int, float, float, float, int)", xGetFunctionAddress("xVertexTexCoords"));
	xRegisterFunction("int xCountVertices(int)", xGetFunctionAddress("xCountVertices"));
	xRegisterFunction("float xVertexX(int, int)", xGetFunctionAddress("xVertexX"));
	xRegisterFunction("float xVertexY(int, int)", xGetFunctionAddress("xVertexY"));
	xRegisterFunction("float xVertexZ(int, int)", xGetFunctionAddress("xVertexZ"));
	xRegisterFunction("float xVertexNX(int, int)", xGetFunctionAddress("xVertexNX"));
	xRegisterFunction("float xVertexNY(int, int)", xGetFunctionAddress("xVertexNY"));
	xRegisterFunction("float xVertexNZ(int, int)", xGetFunctionAddress("xVertexNZ"));
	xRegisterFunction("float xVertexTX(int, int)", xGetFunctionAddress("xVertexTX"));
	xRegisterFunction("float xVertexTY(int, int)", xGetFunctionAddress("xVertexTY"));
	xRegisterFunction("float xVertexTZ(int, int)", xGetFunctionAddress("xVertexTZ"));
	xRegisterFunction("float xVertexBX(int, int)", xGetFunctionAddress("xVertexBX"));
	xRegisterFunction("float xVertexBY(int, int)", xGetFunctionAddress("xVertexBY"));
	xRegisterFunction("float xVertexBZ(int, int)", xGetFunctionAddress("xVertexBZ"));
	xRegisterFunction("float xVertexU(int, int, int)", xGetFunctionAddress("xVertexU"));
	xRegisterFunction("float xVertexV(int, int, int)", xGetFunctionAddress("xVertexV"));
	xRegisterFunction("float xVertexW(int, int, int)", xGetFunctionAddress("xVertexW"));
	xRegisterFunction("float xVertexRed(int, int)", xGetFunctionAddress("xVertexRed"));
	xRegisterFunction("float xVertexGreen(int, int)", xGetFunctionAddress("xVertexGreen"));
	xRegisterFunction("float xVertexBlue(int, int)", xGetFunctionAddress("xVertexBlue"));
	xRegisterFunction("float xVertexAlpha(int, int)", xGetFunctionAddress("xVertexAlpha"));
	xRegisterFunction("int xTriangleVertex(int, int, int)", xGetFunctionAddress("xTriangleVertex"));
	xRegisterFunction("int xCountTriangles(int)", xGetFunctionAddress("xCountTriangles"));
	xRegisterFunction("void xPaintSurface(int, int)", xGetFunctionAddress("xPaintSurface"));
	xRegisterFunction("void xClearSurface(int, int, int)", xGetFunctionAddress("xClearSurface"));
	xRegisterFunction("int xGetSurfaceTexture(int, int)", xGetFunctionAddress("xGetSurfaceTexture"));
	xRegisterFunction("void xFreeSurface(int)", xGetFunctionAddress("xFreeSurface"));
	xRegisterFunction("void xSurfacePrimitiveType(int, int)", xGetFunctionAddress("xSurfacePrimitiveType"));
	xRegisterFunction("void xSurfaceTexture(int, int, int, int)", xGetFunctionAddress("xSurfaceTexture"));
	xRegisterFunction("void xSurfaceColor(int, int, int, int)", xGetFunctionAddress("xSurfaceColor"));
	xRegisterFunction("void xSurfaceAlpha(int, float)", xGetFunctionAddress("xSurfaceAlpha"));
	xRegisterFunction("void xSurfaceShininess(int, float)", xGetFunctionAddress("xSurfaceShininess"));
	xRegisterFunction("void xSurfaceBlend(int, int)", xGetFunctionAddress("xSurfaceBlend"));
	xRegisterFunction("void xSurfaceFX(int, int)", xGetFunctionAddress("xSurfaceFX"));
	xRegisterFunction("void xSurfaceAlphaRef(int, int)", xGetFunctionAddress("xSurfaceAlphaRef"));
	xRegisterFunction("void xSurfaceAlphaFunc(int, int)", xGetFunctionAddress("xSurfaceAlphaFunc"));
	xRegisterFunction("charsArray xCPUName()", xGetFunctionAddress("xCPUName"));
	xRegisterFunction("charsArray xCPUVendor()", xGetFunctionAddress("xCPUVendor"));
	xRegisterFunction("int xCPUFamily()", xGetFunctionAddress("xCPUFamily"));
	xRegisterFunction("int xCPUModel()", xGetFunctionAddress("xCPUModel"));
	xRegisterFunction("int xCPUStepping()", xGetFunctionAddress("xCPUStepping"));
	xRegisterFunction("int xCPUSpeed()", xGetFunctionAddress("xCPUSpeed"));
	xRegisterFunction("charsArray xVideoInfo()", xGetFunctionAddress("xVideoInfo"));
	xRegisterFunction("float xVideoAspectRatio()", xGetFunctionAddress("xVideoAspectRatio"));
	xRegisterFunction("charsArray xVideoAspectRatioStr()", xGetFunctionAddress("xVideoAspectRatioStr"));
	xRegisterFunction("float xGetTotalPhysMem()", xGetFunctionAddress("xGetTotalPhysMem"));
	xRegisterFunction("float xGetAvailPhysMem()", xGetFunctionAddress("xGetAvailPhysMem"));
	xRegisterFunction("float xGetTotalPageMem()", xGetFunctionAddress("xGetTotalPageMem"));
	xRegisterFunction("float xGetAvailPageMem()", xGetFunctionAddress("xGetAvailPageMem"));
	xRegisterFunction("float xGetTotalVidMem()", xGetFunctionAddress("xGetTotalVidMem"));
	xRegisterFunction("float xGetAvailVidMem()", xGetFunctionAddress("xGetAvailVidMem"));
	xRegisterFunction("float xGetTotalVidLocalMem()", xGetFunctionAddress("xGetTotalVidLocalMem"));
	xRegisterFunction("float xGetAvailVidLocalMem()", xGetFunctionAddress("xGetAvailVidLocalMem"));
	xRegisterFunction("float xGetTotalVidNonlocalMem()", xGetFunctionAddress("xGetTotalVidNonlocalMem"));
	xRegisterFunction("float xGetAvailVidNonlocalMem()", xGetFunctionAddress("xGetAvailVidNonlocalMem"));
	xRegisterFunction("int xLoadTerrain(charsArray, int)", xGetFunctionAddress("xLoadTerrain"));
	xRegisterFunction("int xCreateTerrain(int, int)", xGetFunctionAddress("xCreateTerrain"));
	xRegisterFunction("void xTerrainShading(int, int)", xGetFunctionAddress("xTerrainShading"));
	xRegisterFunction("float xTerrainHeight(int, int, int)", xGetFunctionAddress("xTerrainHeight"));
	xRegisterFunction("int xTerrainSize(int)", xGetFunctionAddress("xTerrainSize"));
	xRegisterFunction("float xTerrainX(int, float, float, float)", xGetFunctionAddress("xTerrainX"));
	xRegisterFunction("float xTerrainY(int, float, float, float)", xGetFunctionAddress("xTerrainY"));
	xRegisterFunction("float xTerrainZ(int, float, float, float)", xGetFunctionAddress("xTerrainZ"));
	xRegisterFunction("void xModifyTerrain(int, int, int, float, int)", xGetFunctionAddress("xModifyTerrain"));
	xRegisterFunction("void xTerrainDetail(int, int)", xGetFunctionAddress("xTerrainDetail"));
	xRegisterFunction("void xTerrainSplatting(int, int)", xGetFunctionAddress("xTerrainSplatting"));
	xRegisterFunction("int xLoadTerrainTexture(charsArray)", xGetFunctionAddress("xLoadTerrainTexture"));
	xRegisterFunction("void xFreeTerrainTexture(int)", xGetFunctionAddress("xFreeTerrainTexture"));
	xRegisterFunction("void xTerrainTextureLightmap(int, int)", xGetFunctionAddress("xTerrainTextureLightmap"));
	xRegisterFunction("void xTerrainTexture(int, int)", xGetFunctionAddress("xTerrainTexture"));
	xRegisterFunction("void xTerrainViewZone(int, int, int)", xGetFunctionAddress("xTerrainViewZone"));
	xRegisterFunction("void xTerrainLODs(int)", xGetFunctionAddress("xTerrainLODs"));
	xRegisterFunction("int xTextureWidth(int)", xGetFunctionAddress("xTextureWidth"));
	xRegisterFunction("int xTextureHeight(int)", xGetFunctionAddress("xTextureHeight"));
	xRegisterFunction("int xCreateTexture(int, int, int, int)", xGetFunctionAddress("xCreateTexture"));
	xRegisterFunction("void xFreeTexture(int)", xGetFunctionAddress("xFreeTexture"));
	xRegisterFunction("void xSetTextureFilter(int, int)", xGetFunctionAddress("xSetTextureFilter"));
	xRegisterFunction("void xTextureBlend(int, int)", xGetFunctionAddress("xTextureBlend"));
	xRegisterFunction("void xTextureCoords(int, int)", xGetFunctionAddress("xTextureCoords"));
	xRegisterFunction("void xTextureFilter(charsArray, int)", xGetFunctionAddress("xTextureFilter"));
	xRegisterFunction("void xClearTextureFilters()", xGetFunctionAddress("xClearTextureFilters"));
	xRegisterFunction("int xLoadTexture(charsArray, int)", xGetFunctionAddress("xLoadTexture"));
	xRegisterFunction("charsArray xTextureName(int)", xGetFunctionAddress("xTextureName"));
	xRegisterFunction("void xPositionTexture(int, float, float)", xGetFunctionAddress("xPositionTexture"));
	xRegisterFunction("void xScaleTexture(int, float, float)", xGetFunctionAddress("xScaleTexture"));
	xRegisterFunction("void xRotateTexture(int, float)", xGetFunctionAddress("xRotateTexture"));
	xRegisterFunction("int xLoadAnimTexture(charsArray, int, int, int, int, int)", xGetFunctionAddress("xLoadAnimTexture"));
	xRegisterFunction("int xCreateTextureFromData(int, int, int, int, int)", xGetFunctionAddress("xCreateTextureFromData"));
	xRegisterFunction("int xGetTextureData(int, int)", xGetFunctionAddress("xGetTextureData"));
	xRegisterFunction("int xGetTextureDataPitch(int, int)", xGetFunctionAddress("xGetTextureDataPitch"));
	xRegisterFunction("int xGetTextureSurface(int, int)", xGetFunctionAddress("xGetTextureSurface"));
	xRegisterFunction("int xGetTextureFrames(int)", xGetFunctionAddress("xGetTextureFrames"));
	xRegisterFunction("void xSetCubeFace(int, int)", xGetFunctionAddress("xSetCubeFace"));
	xRegisterFunction("void xSetCubeMode(int, int)", xGetFunctionAddress("xSetCubeMode"));
	xRegisterFunction("float xVectorPitch(float, float, float)", xGetFunctionAddress("xVectorPitch"));
	xRegisterFunction("float xVectorYaw(float, float, float)", xGetFunctionAddress("xVectorYaw"));
	xRegisterFunction("float xDeltaPitch(int, int)", xGetFunctionAddress("xDeltaPitch"));
	xRegisterFunction("float xDeltaYaw(int, int)", xGetFunctionAddress("xDeltaYaw"));
	xRegisterFunction("float xTFormedX()", xGetFunctionAddress("xTFormedX"));
	xRegisterFunction("float xTFormedY()", xGetFunctionAddress("xTFormedY"));
	xRegisterFunction("float xTFormedZ()", xGetFunctionAddress("xTFormedZ"));
	xRegisterFunction("void xTFormPoint(float, float, float, int, int)", xGetFunctionAddress("xTFormPoint"));
	xRegisterFunction("void xTFormVector(float, float, float, int, int)", xGetFunctionAddress("xTFormVector"));
	xRegisterFunction("void xTFormNormal(float, float, float, int, int)", xGetFunctionAddress("xTFormNormal"));
	xRegisterFunction("int xOpenMovie(charsArray)", xGetFunctionAddress("xOpenMovie"));
	xRegisterFunction("void xCloseMovie(int)", xGetFunctionAddress("xCloseMovie"));
	xRegisterFunction("void xDrawMovie(int, int, int, int, int)", xGetFunctionAddress("xDrawMovie"));
	xRegisterFunction("int xMovieWidth(int)", xGetFunctionAddress("xMovieWidth"));
	xRegisterFunction("int xMovieHeight(int)", xGetFunctionAddress("xMovieHeight"));
	xRegisterFunction("int xMoviePlaying(int)", xGetFunctionAddress("xMoviePlaying"));
	xRegisterFunction("void xMovieSeek(int, float, int)", xGetFunctionAddress("xMovieSeek"));
	xRegisterFunction("float xMovieLength(int)", xGetFunctionAddress("xMovieLength"));
	xRegisterFunction("float xMovieCurrentTime(int)", xGetFunctionAddress("xMovieCurrentTime"));
	xRegisterFunction("void xMoviePause(int)", xGetFunctionAddress("xMoviePause"));
	xRegisterFunction("void xMovieResume(int)", xGetFunctionAddress("xMovieResume"));
	xRegisterFunction("int xMovieTexture(int)", xGetFunctionAddress("xMovieTexture"));
	xRegisterFunction("int xCreateWorld()", xGetFunctionAddress("xCreateWorld"));
	xRegisterFunction("void xSetActiveWorld(int)", xGetFunctionAddress("xSetActiveWorld"));
	xRegisterFunction("int xGetActiveWorld()", xGetFunctionAddress("xGetActiveWorld"));
	xRegisterFunction("int xGetDefaultWorld()", xGetFunctionAddress("xGetDefaultWorld"));
	xRegisterFunction("void xDeleteWorld(int)", xGetFunctionAddress("xDeleteWorld"));
